### ISSUE TITLE
Gamepad cannot be made to vibrate

### ISSUE THREAD

**Issue by mcmonkey4eva** [opentk/opentk#336] opened 2016-01-10 03:18 UTC
The code in OpenTK for `SetVibration` is literally just `return false;`.

... That is very much a problem, as I would like to be able to give controller feedback as part of a game.

**Comment by cra0zy** [comment] 2016-02-19 11:45
Duplicate of #81, Closing.

**Closed by cra0zy** 2016-02-19 11:45 UTC
Labels: duplicate
