### ISSUE TITLE
Mousewheel on X11 updating based on global mousewheel position

### ISSUE THREAD

**Issue by jealouscloud** [opentk/opentk#426] opened 2016-09-07 23:04 UTC
### Description

On X11, The mousewheel updates based on the global mousewheel position, instead of only when scrolled in the current window.
INativeWindow.OnMouseWheel and Mouse.GetCursorState are both victim to this..
### Repro steps

I'm on Arch Linux with XInput version 2.3, which means [XI2MouseKeyboard](https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/X11/XI2MouseKeyboard.cs) is used as my input backend.
1. Step A
   Open program that catches mouse wheel activity, for example through INativeWindow.OnMouseWheel
2. Step B
   Use the scroll wheel on any other window, just not on your program
3. Step C
   Click back on your window and it will update your mousewheel with a delta equal to the difference of what you've scrolled outside of your window, potentially jumping the data shown by scrolling simply for multitasking.
### Expected behavior

Mousewheel to only be affected when the mousewheel is used on the window.
### Actual behavior

Mousewheel reacts to all scrolling outside of the window once you perform a mouse event again on a window, like clicking on it.
### Related information
- Arch Linux using linux-4.7.2-1-ARCH, xfce, and lightdm
- Native backend
- Applies to OpenTK develop branch and 1.1.4
- Mono
- Workarounds:
  I've found that removing [this code in X11GLNative.cs](https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/X11/X11GLNative.cs#L916-L925) to disable "High resoultion scroll events" works fine, but I think that [XI2MouseKeyboard.cs](https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/X11/XI2MouseKeyboard.cs) is the file that requires a patch in order to use relative scrolling properly _and_ still have high resolution scroll events.

I'd have set up a pull request but I don't know how to properly fix the X11 code in XI2MouseKeyboard

**Comment by varon** [comment] 2016-09-08 08:55
Thanks for the very clear report.

I'm not sure if this is a bug. You can easily work around it by tracking where the mouse is, whether the window is focused, and a wheel scroll state variable.

If we implemented your expected behaviour, we'd lose the ability to track mouse motions when the window is focused or not hovered, which seems like a loss of functionality.

**Comment by jealouscloud** [comment] 2016-09-08 11:47
It must be, because the difference between high resolution scroll events and normal events should be the fact high resolution events have more precision through a decimal point. Instead, it's a drastically different number, and it's inconsistent with behavior on other platforms like Windows.

**Comment by varon** [comment] 2016-09-08 12:31
How are you accessing the scroll state in your event listener?
On Windows, I get the following:
`MouseWheelEventArgs` parameter -> focus only scrolling.
`Mouse.GetCursorState()` -> includes scrolling done outside of the window too.

The event is only fired when your cursor scrolls IN the window, though.

Do you observe anything differently to this?

**Comment by jealouscloud** [comment] 2016-09-08 13:06
GetCursorState is global on my setup too. MouseWheelEventArgs is also global, including Delta, DeltaPrecise, Value, and ValluePrecise, which is the problem.

**Comment by varon** [comment] 2016-09-08 14:32
@cra0zy  - any ideas on this? IIRC you're also using Linux.

**Comment by cra0zy** [comment] 2016-09-08 14:52
I am using Arch Linux as well. Anyway I am doing some system reinstallations right now, once I'm done I'll look into this.

@jealouscloud Does the bug occur with SDL backend? We will probably be dropping the native backends sometime soon.

**Comment by varon** [comment] 2016-12-02 06:46
@cra0zy did you ever look at this?

**Comment by varon** [comment] 2017-06-11 22:48
Closing due to no feedback and age.

**Comment by varon** [comment] 2017-06-11 22:49
If this is still affecting you, @jealouscloud  - please do let us know and I can re-open it.

**Closed by varon** 2017-06-11 22:48 UTC
