### ISSUE TITLE
Matrix4.CreateTranslation() creates unexpected translation

### ISSUE THREAD

**Issue by molor824** [opentk/opentk#1499] opened 2022-09-04 05:39 UTC
### Description

When translation matrix created via CreateTranslation() gets multiplied by Vector4, Vector4 gets translated unexpectedly

### Repro steps

1. Create translation matrix via CreateTranslation() (preferably non zero numbers)
2. Multiply it with Vector4
3. Print out Vector4 to see unexpected translation

### Expected behavior

Translate Vector4 correctly as expected

### Actual behavior

Unexpected random Vector4 translation

### Related information 

* Operating system: Windows 10
* SDL or Native backend (if using OpenTK 3.x): GLFW
* What version of OpenTK (Installer, NuGet, Source Code): 4.7.4
* What runtime (.NET Framework, CoreCLR, Mono): .NET
* Workarounds (if any): Set translation matrix manually, by setting last column as (x, y, z, 1)

**Comment by NogginBops** [comment] 2022-09-04 10:12
This issue would be much more descriptive with actual numbers and what numbers you expect to see. And I would also like to see a concrete code snippet that shows the creation and multiplication of the matrix.

My guess is that you are seeing weird results because OpenTK has row major matrices and you might be expecting column major matrices.

**Comment by NogginBops** [comment] 2022-09-04 13:13
You have to show more code. 
Show how you upload the matrix and how you use it in your shader.

> if OpenTK uses row major matrices, wouldnt rest of the functions would follow and have no effect?
not sure what this means tbh

**Comment by NogginBops** [comment] 2022-11-23 23:02
Closing this issue as no more information has been provided.
Likely the issue is the multiplication order of the translation, rotation and scale that should probably be the other way around.

**Closed by NogginBops** 2022-11-23 23:02 UTC
Labels: needs verification, 4.x, math
