### ISSUE TITLE
Cannot create a GraphicsContext in .NETCore applications.

### ISSUE THREAD

**Issue by loicmorvan** [opentk/opentk#569] opened 2017-07-11 17:51 UTC
### Description

Cannot create a GraphicsContext in .NETCore applications.

### Repro steps

1. Create a new application project in .NETCore App 1.1.
2. Reference the Nuget package OpenTK.NETCore 1.1.2737.6432 (the only version available).
3. Put this code in Program.cs:

```cs
using OpenTK;
using OpenTK.Graphics;

namespace Sample
{
    class Program
    {
        static void Main(string[] args)
        {
            var window = new NativeWindow();

            var graphicsContext = new GraphicsContext(GraphicsMode.Default, window.WindowInfo, 4, 0, GraphicsContextFlags.ForwardCompatible);
        }
    }
}
```
4. Build and run this program.

### Expected behavior

The program launches and exits without exception.

### Actual behavior

This exception shows up:
```
Unhandled Exception: System.MethodAccessException: Attempt by method 'OpenTK.Platform.Windows.Wgl+Arb.GetExtensionsString(IntPtr)' to access method 'OpenTK.BindingsBase.PtrToStringUtf8(IntPtr)' failed.
   at OpenTK.Platform.Windows.Wgl.Arb.GetExtensionsString(IntPtr hdc)
   at OpenTK.Platform.Windows.Wgl.SupportsExtension(IntPtr dc, String name)
   at OpenTK.Platform.Windows.WinGraphicsMode.ChoosePixelFormatARB(IntPtr device, GraphicsMode desired_mode)
   at OpenTK.Platform.Windows.WinGraphicsMode.SelectGraphicsMode(ColorFormat color, Int32 depth, Int32 stencil, Int32 samples, ColorFormat accum, Int32 buffers, Boolean stereo)
   at OpenTK.Platform.Windows.WinGLContext.SetGraphicsModePFD(WinGraphicsMode mode_selector, GraphicsMode mode, WinWindowInfo window)
   at OpenTK.Platform.Windows.WinGLContext..ctor(GraphicsMode format, WinWindowInfo window, IGraphicsContext sharedContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Platform.Windows.WinFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
```

### Related information 

* Windows 10 x64
* Native backend (OpenGL.dll)
* Nuget package OpenTK.NETCore 1.1.2737.6432
* .NETCore 1.1
* No workaround that I know.

Thank you!

**Comment by mellinoe** [comment] 2017-07-11 18:17
Just a note: OpenTK.NETCore is an unofficial fork I made a while back to support .NET Core. It's missing a lot of fixes and features from mainline OpenTK.

This seems to be caused by a bug fix to string marshalling that I attempted to make recently. For the time being you can revert back to version 1.1.2571.6431 and things should work. I'll try to fix this bug sometime, though.

**Comment by mellinoe** [comment] 2017-07-11 18:24
Yeah -- I figured out what the issue is. I will publish a newer version later today.

**Comment by loicmorvan** [comment] 2017-07-11 18:39
Ok, thanks.
I think we already had a discussion about that, but do you plan to officially support NetCore or NetStandard?

**Comment by loicmorvan** [comment] 2017-07-11 18:45
For information, taking the previous version did work, so thanks again.

**Comment by mellinoe** [comment] 2017-07-11 18:57
I'd love to just get my changes back into the regular version. @varon I think the last I heard, the build tool just needed to support .NET Core. Is that working yet?

> For information, taking the previous version did work, so thanks again.

No problem. Just note that functions which return strings don't work correctly in that version. That's a very small set of things, like `GL.GetString`. That was the bug I fixed in the very latest version.

**Comment by Nihlus** [comment] 2017-07-11 20:51
@mellinoe There are some more things which need to happen, such as using something else for bitmaps, but the main thing is a dynamic library loader since there's no equivalent of dllmap in the .NET Standard, and the rewriter as you mentioned. I've integrated and improved your native library handler in a local branch, and experimented with the rewriter in another. It should be fairly painless to port once .NET Standard 2.0 is officially out :smile: 

We are planning on doing it as a part of the library split, to properly mark the transition and to piggyback on what's going to be a large structural change anyway. We might do an inbetweeny version which also supports the standard, but we'll have to talk about and plan that internally.

I'm closing this issue as well, since it's not about OpenTK itself, but rather a fork.

**Closed by Nihlus** 2017-07-11 20:51 UTC

**Comment by JimSEOW** [comment] 2017-07-11 21:38
@mellinoe  Please check the discussion on [OpenGLES UWP XAML interop for C#](https://github.com/Microsoft/HoloJS/issues/57#issuecomment-314534809)
