### ISSUE TITLE
Mouse clicks not detected after second window opens

### ISSUE THREAD

**Issue by ala53** [opentk/opentk#321] opened 2015-12-14 23:53 UTC
Manifested as mono/MonoGame#4297

When 2 GameWindows are opened (in my case in 2 separate AppDomains), input (keyboard and mouse move) on the first window works, but it fails to detect Left & Right clicks. The second window works perfectly.

Mouse state always returns as:

```
{
  "Wheel": 0,
  "WheelPrecise": 0.0,
  "Scroll": {
    "X": 0.0,
    "Y": 0.0
  },
  "X": XXX,
  "Y": YYY,
  "LeftButton": 0,
  "MiddleButton": 0,
  "RightButton": 0,
  "XButton1": 0,
  "XButton2": 0,
  "ScrollWheelValue": 0,
  "IsConnected": true
}
```

**Comment by Frassle** [comment] 2015-12-16 09:50
Confirmed, looks like a RawInput issue.

**Comment by Frassle** [comment] 2015-12-16 10:28
Diagnosis:

OpenTK creates a new hidden window on a background thread to listen for RawInput messages. We register RawInput for each device class with this window so INPUT messages get delivered to it.
The issues seems to be that when starting a new AppDomain the window is created and registered again, but RawInput is a process level registration so the first window just stops receiving messages.

We need to make sure only one window is created for all AppDomains in the process.

**Comment by ala53** [comment] 2015-12-16 21:13
Is deriving `RawInputDriver` from `MarshalByRefObject` an acceptable workaround?

**Comment by Frassle** [comment] 2015-12-18 00:44
I think I've manage to put something together with some window lookups and winproc chaining.

I've got a test running two processes, each with two app domains each with it's own GameWindow and all of the them are getting the correct mouse state.

Only downside is getting the odd memory corruption so I've missed something somewhere.

**Comment by Frassle** [comment] 2015-12-24 00:33
Ok this is hell'a more complex than it initially looked. Will think about it some more.

**Comment by varon** [comment] 2017-06-11 18:08
Closing due to age. Please re-open if this issue is still affecting you.

**Closed by varon** 2017-06-11 18:08 UTC
Labels: bug, input
