### ISSUE TITLE
Mac, System.DllNotFoundException: openal32.dll

### ISSUE THREAD

**Issue by 105th** [opentk/opentk#307] opened 2015-10-27 14:36 UTC
I`ve tried to build an project with installed OpenTK as nuget-package and got this error.

``` bash
Unhandled Exception:
System.DllNotFoundException: openal32.dll
  at (wrapper managed-to-native) OpenTK.Audio.OpenAL.AL:GenSourcesPrivate (int,uint*)
  at OpenTK.Audio.OpenAL.AL.GenSources (Int32 n, System.UInt32& sources) [0x00000] in <filename unknown>:0 
  at OpenTK.Audio.OpenAL.AL.GenSource (System.UInt32& source) [0x00000] in <filename unknown>:0 
  at HomeTask10.MainClass.Main (System.String[] args) [0x00001] in /Users/dima/Dropbox/Code/C# .Net/Projects/Alarm, Delegates, Thread (HomeTask10.09.15)/HomeTask10.09.15/Program.cs:52 
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: openal32.dll
  at (wrapper managed-to-native) OpenTK.Audio.OpenAL.AL:GenSourcesPrivate (int,uint*)
  at OpenTK.Audio.OpenAL.AL.GenSources (Int32 n, System.UInt32& sources) [0x00000] in <filename unknown>:0 
  at OpenTK.Audio.OpenAL.AL.GenSource (System.UInt32& source) [0x00000] in <filename unknown>:0 
  at HomeTask10.MainClass.Main (System.String[] args) [0x00001] in /Users/dima/Dropbox/Code/C# .Net/Projects/Alarm, Delegates, Thread (HomeTask10.09.15)/HomeTask10.09.15/Program.cs:52 
```

Here my code:

``` cs
        public static void Main(string[] args)
        {
            uint MySource;
            AL.GenSource(out MySource);
            AL.Source(MySource, ALSourcei.Buffer, 10);
            AL.SourcePlay(MySource); // start playback
            AL.Source(MySource, ALSourceb.Looping, true); // source loops infinitely
            Console.ReadLine(); // wait for keystroke before exiting
            AL.SourceStop(MySource); // halt playback
            AL.DeleteSource(ref MySource);
            // now delete Buffer Objects and dispose the AudioContext
        }
```

**Comment by Frassle** [comment] 2015-11-01 09:32
This is probably because the opentk.config isn't copied with the opentk.dll. mono needs it to know what the OSX name for openal.dll is.

**Comment by ilexp** [comment] 2015-11-01 23:06
This might be a duplicate of #300. Different operating system, but both non-Windows with openal32.dll not being found. Both potentially caused by a missing or invalid .config file.

**Comment by 105th** [comment] 2015-11-03 17:53
@Frassle @ilexp I correctly think that this is the file .config ("packages" is the directory in my project folder)?
![1446572385321](https://cloud.githubusercontent.com/assets/11395678/10916130/0c56da2a-826b-11e5-90fc-4ffb55022279.png)
I opened it:
```xml
<configuration>
  <dllmap os="linux" dll="opengl32.dll" target="libGL.so.1"/>
  <dllmap os="linux" dll="glu32.dll" target="libGLU.so.1"/>
  <dllmap os="linux" dll="openal32.dll" target="libopenal.so.1"/>
  <dllmap os="linux" dll="alut.dll" target="libalut.so.0"/>
  <dllmap os="linux" dll="opencl.dll" target="libOpenCL.so"/>
  <dllmap os="linux" dll="libX11" target="libX11.so.6"/>
  <dllmap os="linux" dll="libXi" target="libXi.so.6"/>
  <dllmap os="linux" dll="SDL2.dll" target="libSDL2-2.0.so.0"/>
  <dllmap os="osx" dll="opengl32.dll" target="/System/Library/Frameworks/OpenGL.framework/OpenGL"/>
  <dllmap os="osx" dll="openal32.dll" target="/System/Library/Frameworks/OpenAL.framework/OpenAL" />
  <dllmap os="osx" dll="alut.dll" target="/System/Library/Frameworks/OpenAL.framework/OpenAL" />
  <dllmap os="osx" dll="libGLES.dll" target="/System/Library/Frameworks/OpenGLES.framework/OpenGLES" />
  <dllmap os="osx" dll="libGLESv1_CM.dll" target="/System/Library/Frameworks/OpenGLES.framework/OpenGLES" />
  <dllmap os="osx" dll="libGLESv2.dll" target="/System/Library/Frameworks/OpenGLES.framework/OpenGLES" />
  <dllmap os="osx" dll="opencl.dll" target="/System/Library/Frameworks/OpenCL.framework/OpenCL"/>
  <dllmap os="osx" dll="SDL2.dll" target="libSDL2.dylib"/>
  <!-- XQuartz compatibility (X11 on Mac) -->
  <dllmap os="osx" dll="libGL.so.1" target="/usr/X11/lib/libGL.dylib"/>
  <dllmap os="osx" dll="libX11" target="/usr/X11/lib/libX11.dylib"/>
  <dllmap os="osx" dll="libXcursor.so.1" target="/usr/X11/lib/libXcursor.dylib"/>
  <dllmap os="osx" dll="libXi" target="/usr/X11/lib/libXi.dylib"/>
  <dllmap os="osx" dll="libXinerama" target="/usr/X11/lib/libXinerama.dylib"/>
  <dllmap os="osx" dll="libXrandr.so.2" target="/usr/X11/lib/libXrandr.dylib"/>
</configuration>
```

And there was this:
![e5141ed318](https://cloud.githubusercontent.com/assets/11395678/10916316/f6ccad96-826b-11e5-874e-3cd52ecf7b6b.png)

Maybe the reason is in the other or something I did not understand?

**Comment by Frassle** [comment] 2015-11-03 20:49
Which folder has your executable program in it? You need OpenTK.dll and OpenTK.dll.config in the same folder as your program executable.

**Comment by 105th** [comment] 2015-11-04 11:53
@Frassle i have used Xamarin with Mono Framework to write code in c#.
I`ve installed NuGet-package called "OpenTK" via Xamarin:
![85b103433db74b4e86b3f23a2a632698](https://cloud.githubusercontent.com/assets/11395678/10937309/0f9ca2da-8303-11e5-810b-0faade2f010b.png)

And this is my folder with project:
![1446637867841](https://cloud.githubusercontent.com/assets/11395678/10937409/ab866230-8303-11e5-8d16-bfae696ebe1a.png)
"OldSpice.mp3" - sound which i want to play

**Comment by Frassle** [comment] 2015-11-04 12:01
Copy OpenTK.dll.config into bin/Debug. Then run the application (HomeTask10.09.15.exe) in that folder.

**Comment by 105th** [comment] 2015-11-06 12:16
@Frassle omg, it works!!!
Thank you!
I spent so much time to understand whats wrong

**Closed** 2017-06-11 18:06 UTC
Labels: bug
