### ISSUE TITLE
GL.VertexAttribPointer inserts GL.BindBuffer call

### ISSUE THREAD

**Issue by Warpten** [opentk/opentk#545] opened 2017-06-18 21:03 UTC
### Description

On `3.0.0-prerelease` (Also tested on an old 2014 build of OpenTK, so likely any version (?)), invoking `OpenTK.Graphics.OpenGL.GL.VertexAttribPointer` inserts a garbage `glBindBuffer` call.

This is hardly noticeable in real-world usage of OpenTK, but using it with [RenderDoc](https://github.com/baldurk/renderdoc) brings out the issue by having OpenGL coincidentally load buffers allocated by RenderDoc.

### Repro steps

I'm not sure I can give you any sample code, but looking at the series of API calls in [apiTrace](https://github.com/apitrace/apitrace) really shows the issue.

```C#
            VAO = GL.GenVertexArray();
            GL.BindVertexArray(VAO);

            VBO = GL.GenBuffer();
            GL.BindBuffer(BufferTarget.ArrayBuffer, VBO);
            GL.BufferData(BufferTarget.ArrayBuffer, new IntPtr(vertices.Length * SizeCache<T>.Size), vertices, BufferUsageHint.StaticDraw);

            EBO = GL.GenBuffer();
            GL.BindBuffer(BufferTarget.ElementArrayBuffer, EBO);
            GL.BufferData(BufferTarget.ElementArrayBuffer, new IntPtr(indices.Length * SizeCache<U>.Size), indices, BufferUsageHint.StaticDraw);

            GL.VertexAttribPointer(0, 3, VertexAttribPointerType.Float, false, SizeCache<Vector3>.Size, 0);
            GL.EnableVertexAttribArray(0);
```

![](http://i.imgur.com/hdzxapH.png)

### Expected behavior

No `glBindBuffer` should be emitted.

### Actual behavior

An extra call with erroneous data is emitted.

### Related information 

* Win10 x86
* Native
* OpenTK 3.0.0-prerelease NuGet
* .NET Framework

**Comment by Warpten** [comment] 2017-06-18 21:16
It escaped my attention but it appears to be even worse: it creates a new buffer, pushes 64 bytes of garbage into it, and binds another one

**Comment by Warpten** [comment] 2017-06-19 07:07
Please find [here](https://github.com/opentk/opentk/files/1084065/MeshViewer.BugTest.zip) a sample application showcasing the issue.

I threw this very quickly together, the cube does not render properly on screen (probably just a viewport issue), but you can still see it blink.

Launching this sample from inside RenderDoc causes no geometry to be drawn on screen.

**Comment by UnknownShadow200** [comment] 2017-06-19 10:34
I'm not seeing the issue with gDEBugger and the sample application
![_gl](https://user-images.githubusercontent.com/6509348/27281220-42533046-552e-11e7-8740-8b13bd0b2688.png)

Also changing so it wasn't run on a separate thread from creation
```CSharp
		protected override void OnPaint(PaintEventArgs e)
		{
			GL.Clear(ClearBufferMask.ColorBufferBit);
			_sample.Render();
			tabControl1.SwapBuffers();
			base.OnPaint(e);
		}
```
fixed not rendering for me

**Comment by Warpten** [comment] 2017-06-19 11:25
You can keep calling Invalidate() in the separate thread and that will take care of rendering multiple frames.

This is odd. I know one other person with that bug... I will try to update my drivers but I really doubt that's what it is because I have this issue both when running my program on the iGPU, and on my GTX 1070.

**Comment by leezer3** [comment] 2017-06-19 13:40
Can't reproduce here either (GTX670) with gDebugger.

I'd test with gDebugger at your end first- I wonder if one of the two has a bug in it.

**Comment by Warpten** [comment] 2017-06-27 19:21
Appears to be some weird bug, either my driver or smth. I seemingly fixed it by rewriting everything - don't ask me.

I haven't ran apitrace / gDebugger etc. Will do by the end of the week

**Comment by Nihlus** [comment] 2017-07-11 20:53
@Warpten I'm going to close this issue, since we've not been able to reproduce it elsewhere. I attribute it to demons in your motherboard - call an exorcist.

If it does resurface, I'll reopen it.

**Closed by Nihlus** 2017-07-11 20:53 UTC
