### ISSUE TITLE
Undocumented change in >= OpenTK 4.0.0 pre9.2 causes missing context

### ISSUE THREAD

**Issue by djgaven588** [opentk/opentk#1118] opened 2020-09-01 08:47 UTC
### Description
In OpenTK 4.0.0 pre9.2, a pull request was included which changed a previous behavior in a breaking way. The pull request in question was https://github.com/opentk/opentk/pull/1096. This pull request changed that context was not provided by default to the rendering loop, and required you to gain context. The change was created for multithreaded setups, but breaks existing projects. Perhaps changing the default behavior to make the rendering thread current, and allow an override in a window setting to use the new behavior.

### Repro steps

Please provide the steps required to reproduce the problem

1. Setup a basic GameWindow, like demonstrated in https://opentk.net/learn/chapter1/1-creating-a-window.html

2. Run any OpenGL call

### Expected behavior

It is expected that context would default to the rendering thread

### Actual behavior

Context is not by default available in the rendering thread

### Related information
The fix to this problem is to simply call MakeCurrent() in OnLoad.
https://discordapp.com/channels/337627185248468993/525453014618865664/750272402344116255

**Comment by NoneGiven** [comment] 2020-09-12 01:12
Dupe of #1100, but this issue is more concise so I vote for keeping this and closing the other.

**Comment by jvbsl** [comment] 2020-09-16 18:09
Should be fixed by https://github.com/opentk/opentk/pull/1122

**Closed by jvbsl** 2020-09-16 18:09 UTC
