### ISSUE TITLE
"CursorVisible = true" causes cursor to snap back to into window bounds

### ISSUE THREAD

**Issue by copygirl** [opentk/opentk#696] opened 2017-12-24 10:47 UTC
### Description

When the game window loses focus, the mouse cursor snaps back into the window bounds once.

I noticed this in a game I was trying to debug something for, as well. As I was trying to create a basic test to verify another issue (which appears to be fixed already), I re-encountered this bug.

### Repro steps

This appears to happen even with the most trivial setup: `new GameWindow().Run()`
For reference I made a project that has some additional unrelated code: [opentk-mouse-issue](https://github.com/copygirl/opentk-mouse-issue)

1. Focus really hard on the window.
2. Unfocus the window, either by clicking the mouse outside the window or tabbing to another application, showing it that you don't want to give it attention right now.
3. Observe the window clinging onto your mouse, desperately longing for your love and care. Maybe you give it focus again without meaning to, but you know it wouldn't work out in the end. Also it's just a window. They don't actually feel anything. Don't be silly. Merry Christmas!

### Related information 

- **Operating system:** Arch Linux (using Xfce)
- **SDL or Native backend:** ?
- **OpenTK version:** `3.0.0-git00008`
- **What runtime:** Mono `5.0.0`

Let me know if you need me to provide any additional information.

**Comment by Nihlus** [comment] 2018-01-01 17:55
I can't reproduce this issue on Linux Mint 18.3, using the latest development build from myget. Are you still experiencing it on Xfce?

**Comment by copygirl** [comment] 2018-01-01 18:24
The "snapping back" appears to be from calling `CursorVisible = true`. If the cursor is already visible, the mouse is still reset to the last known position within the window..? I can also cause it by calling it manually - [in my example project I can do this by pressing any key](https://github.com/copygirl/opentk-mouse-issue/blob/master/Game.cs#L26-L27). I suppose `CursorVisible` is also set back to true when the window loses focus, which runs the code that's responsible for this behavior..? Maybe it shouldn't run if the cursor is already visible?

I actually found it strange that making the cursor visible again causes it to jump back to the location where it was made invisible, instead of, in my case, re-appearing at the center of the screen. Is this intentionally done by OpenTK or perhaps a side-effect of my setup?

I will have a look into OpenTK's code, perhaps I can help out.

**Comment by Nihlus** [comment] 2018-01-01 18:27
Aha, then this is a duplicate of #668. Hop over there!

**Closed by Nihlus** 2018-01-01 18:27 UTC
Labels: bug, input, os / linux / x11

**Comment by copygirl** [comment] 2018-01-01 19:12
Seeing if I can perhaps provide a PR, is it okay if I ask a question?

Why does [`NativeWindow.CursorVisible`](https://github.com/opentk/opentk/blob/develop/src/OpenTK/NativeWindow.cs#L477-L485) not just delegate to the implementation's `CursorVisible`? Currently, this is what it looks like:
```csharp
public bool CursorVisible {
    get { return cursor_visible; }
    set {
        cursor_visible = value;
        implementation.CursorVisible = value;
    }
}
```
If you were to continue using `cursor_visible` like this, I would recommend adding this to the setter:
`if (value == cursor_visible) return;`

But perhaps it would make more sense to have this be done by the implementations themselves, considering they all seem to have their own private fields to store cursor visibility anyway, rather than querying for cursor visibility each time - in which case I could understand this decision.

I think I'll just create a PR with what I think is good. Might take a while as I want to make sure I can at least test the changes. That way I can also see if I can provide and test some Linux related issues / fixes.

**Comment by Frassle** [comment] 2018-01-01 19:50
> But perhaps it would make more sense to have this be done by the implementations themselves, 

I agree, that sounds like a sensible change. If you want to PR just that change to start it would get you comfortable with the workflows.
