### ISSUE TITLE
GLFW.PollEvents() throws exception after garbage collection

### ISSUE THREAD

**Issue by 128-bit-guy** [opentk/opentk#1073] opened 2020-05-27 13:23 UTC
### Description

When i invoke GLFW.PollEvents after GC exception is thrown:
https://gist.github.com/128-bit-guy/63647d82f9bf8f52ec1063280d424f1e

### Repro steps

1. Add some GLFW Callback
2. Run GC
3. Do something to trigger this callback
4. Invoke GLFW.PollEvents()

https://gist.github.com/128-bit-guy/7dad05e2fa3880052b6f5547c1cc4b9a

### Expected behavior

GLFW.PollEvents() should not throw exception

### Actual behavior

This exception is thrown:
https://gist.github.com/128-bit-guy/63647d82f9bf8f52ec1063280d424f1e

### Related information 

* Operating system: Windows 10
* SDL or Native backend: ?
* What version of OpenTK: NuGet 4.0.0-Pre9.1
* What runtime: CoreCLR
* Workarounds: Keep reference to delegate somewhere in your code

**Comment by NogginBops** [comment] 2020-05-27 17:22
Well this is kind of not a bug (but might be considered one), because the function `GLFW.SetFramebufferSizeCallback()` doesn't save a reference to the delegate the GC thinks it can collect the delegate and GC the stub at the same time. So for this to work you need to keep the reference to the delegate alive.

I think that in theory we can keep the reference ourselves, but I think someone had a good reason as to why we shouldn't.

At least you have a workaround for the issue either way.

**Comment by 128-bit-guy** [comment] 2020-05-28 11:15
> 
> 
> Well this is kind of not a bug (but might be considered one), because the function `GLFW.SetFramebufferSizeCallback()` doesn't save a reference to the delegate the GC thinks it can collect the delegate and GC the stub at the same time. So for this to work you need to keep the reference to the delegate alive.
> 
> I think that in theory we can keep the reference ourselves, but I think someone had a good reason as to why we shouldn't.
> 
> At least you have a workaround for the issue either way.

I added workaround to list. I still think that this is a bug, because there is a reference to delegate in native code, but it gets deleted.

**Comment by NogginBops** [comment] 2020-05-28 13:16
Yeah I'm also of the opinion that this should be fixed, but I think someone had a reason for why we shouldn't keep the reference (but I can't remember who).

**Comment by NogginBops** [comment] 2022-08-09 00:14
I've decided we should probably keep these references ourselves, so I will make a fix for it for some future version of OpenTK.

**Comment by NogginBops** [comment] 2023-06-12 18:57
I've decided that because we would have to store the references per window (as that is how GLFW handles the callbacks) we will not be holding on to these references ourselves. This would complicate the bindings code and add inefficiencies that are avoided if users keep their own references.

**Closed by NogginBops** 2023-06-12 18:57 UTC
Labels: 4.x, glfw
