### ISSUE TITLE
Overload for GL.ProgramUniform[1,2,3,4](int program, int location, int count, uint* value) is missing

### ISSUE THREAD

**Issue by ghost** [opentk/opentk#1367] opened 2022-01-15 03:02 UTC
### Repro steps

```csharp
...
int program = GL.CreateProgram();
int location = somewhere;
const int count = 1;
fixed(uint* ptr = somewhereElse) {
    GL.ProgramUniform1(program, location, count, ptr); // Throws because the overload doesn't exist.
    // Any of the four variants; ProgramUniform1, ProgramUniform2, ProgramUniform3, and ProgramUniform4 has the same behavior.
}
...
```

### Expected behavior

Existing overloads for these parameters.

### Actual behavior

Missing overloads. Already clarified above.

### Related information 

Overload for `GL.ProgramUniform[1,2,3,4](uint program, int location, int count, uint* value)` exists.
*Note the uint for the program parameter instead of int.*

Overload for `GL.Uniform[1,2,3,4](int location, int count, uint* value)` also exists.

So it would make sense to add these missing overloads.

* OS: Windows 10
* Version of OpenTK: NuGet OpenTK main package. Latest version on NuGet as of when writing this issue. (4.6.7)
* Runtime: .NET 6.0
* Workarounds: Bind program and use `GL.Uniform[1,2,3,4](...)` instead, but it's not preferable.

**Comment by NogginBops** [comment] 2022-01-18 20:02
We likely won't be fixing this in OpenTK 4 as the bindings generator is hard to work with and the current maintainers don't have much experience with it.

There is a workaround for this issue:
Use the `uint` program overload by simply casting the program argument to `uint` (and wrapping that in an `unsafe` block to properly handle negative numbers).
```cs
// This is the overload
void ProgramUniform1(uint program, int location, int count, uint* value)

// This is how to call it with an "int program" variable
unchecked
{
    ProgramUniform1((uint)program, location, count, ptr);
}
```

**Comment by wildniklin** [comment] 2022-01-18 22:06
That's another way to do it.
Is there some way to implement extra methods to the GL class without having to install the open-source version?

###### Related?: (I don't want to be spammy and make another issue dedicated to this)
###### I've had some problems when trying the open-source version of OpenTK, it just wouldn't build in Visual Studio. Tried doing the steps in [this issue](https://github.com/opentk/opentk/issues/1222#issuecomment-749684287). Maybe I'm just stupid, or something. Steps to reproduce: Download the release .zip (4.7.6), extract it, open the solution file (.sln, in Visual Studio 2022), and then a lot of errors started flowing in, tried building in VS, errors, ran the build.cmd file in the solution folder, still errors, rebuilt in VS, still errors... and then as some of you suggested, removing the unused projects did not clear the errors, even after rebuilding both with .cmd and VS. There were missing enums before I even touched anything.
###### What am I doing wrong here?

Will this missing overload be fixed in 5.x though?

**Comment by NogginBops** [comment] 2022-01-18 22:24
Unfortunately it's hard to extend the `GL` class with additional overloads, you can make your own functions but they will not live in `GL`. To make your own overloads you need to create the appropriate function pointer and then call that function pointer in a static wrapper function. I can give you more information about this if you don't want to use this workaround (we have a discord too that you can use for more conversational support questions, but I'm fine with taking it here or in a new dedicated issue).

In OpenTK 5.0 this overload will be fixed.

**Comment by wildniklin** [comment] 2022-01-18 22:57
> Unfortunately it's hard to extend the `GL` class with additional overloads, you can make your own functions but they will not live in `GL`.

That's a shame...

> To make your own overloads you need to create the appropriate function pointer and then call that function pointer in a static wrapper function.

I've tried porting OpenGL to C# with thousands- perhaps even tens of thousands of lines, it was hell, and yet, it didn't work.

> I can give you more information about this if you don't want to use this workaround

Please do.
I'm still having trouble understanding how everything builds and stuff, I've even tried to learn and use C++ instead, but it just got too confusing, so I gave up.

Taking this in a new dedicated issue could be good, for the future visitors having the same issue.

> In OpenTK 5.0 this overload will be fixed.

Thanks. :)

Is there any way I can DM you? I'd clarify more stuff that way.

**Comment by NogginBops** [comment] 2022-01-18 23:00
We can create a dedicated issue for that then :)
I don't think github allows for DMs but if you have a discord account you could talk to us more in the OpenTK server, other than that I think github issues are fine personally.

**Comment by wildniklin** [comment] 2022-01-19 17:22
> you could talk to us more in the OpenTK server

You may have noticed that I am a bit hesitant in joining the discord server, that's because I am hesitant...
I have social anxiety, and that stuff. Sorry about that. My social skills are absolutely terrible.

Even though it's way more convenient to talk in the server, I still prefer to DM privately on discord or anything rather than to talk publicly in a discord server.

**Comment by NogginBops** [comment] 2022-04-19 23:20
I've looked at the generated overloads for OpenTK 5 and this should be fixed.

**Closed by NogginBops** 2022-04-19 23:20 UTC
Labels: bug, wontfix, 4.x, 3.x, fixed-by-5.0
