### ISSUE TITLE
OpenTK.GLControl.dll has an invalid Strong Name

### ISSUE THREAD

**Issue by oleneveu** [opentk/opentk#859] opened 2018-11-17 00:34 UTC
### Description

The OpenTK.GLControl assembly has an invalid strong name, and thus cannot be deployed using 'Click-Once' as all assemblies have their strong name checked during the installation (if they have one).

### Repro steps

There is no need to create a click-once deployment to check this issue, the strong name of an assembly can be checked using the 'sn.exe' tool provided with the .net SDK.

From the 'Developper Command Prompt' , run the command:
```
C:\Dev\GLBuilder\packages\OpenTK.GLControl.3.0.1\lib\net20>sn -vf OpenTK.GLControl.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.
```

### Expected behavior

Well, obviously having a valid strong name on the assembly would solve the issue...
But as I could not find any other related post, maybe removing the strong name could be an option.

### Related information 

This issue is present for both the 3.0.0 and the 3.0.1 NuGet packages.

The only quick workaround I found was to remove the strong name from the compiled assembly (see: https://stackoverflow.com/a/38717200/2656835). However I am a bit concerned about the possible side effects.

**Comment by varon** [comment] 2019-03-27 10:36
Did we ever find out if this was the cause?

**Comment by Perksey** [comment] 2019-03-27 19:44
I don't think so.

**Comment by Hitch1980** [comment] 2019-04-25 13:52
My workaround was to resign the dll with a personal snk using Strong.Name.Helper v1.0.7. I don't like the solution because I can not use the nuget package anymore but it works...

It will be awesome if that will be correctly signed in the next version.

**Comment by jvbsl** [comment] 2019-04-25 15:25
as strong names are not recommended anymore(because what they were supposed to do can be circumvented with later added features), it would not get any strong name at all. At least that's what was once talked about

**Comment by Hitch1980** [comment] 2019-04-25 16:43
I guess that strong names shouldn’t be used for security reason but do we know which solution is recommended in our case and for the next version ?

**Comment by Perksey** [comment] 2019-04-28 12:57
In 4.0 we won't sign our assemblies, not completely sure what to do for 3.0.

**Comment by varon** [comment] 2019-05-03 12:39
@Hitch1980  - Does the not-signed DLL work as expected without the Crashes in #432 ?

**Comment by Hitch1980** [comment] 2019-05-03 12:51
> @Hitch1980 - Does the not-signed DLL work as expected without the Crashes in #432 ?

It works but not for a ClickOnce solution

**Comment by varon** [comment] 2020-11-25 20:05
GLControl is largely obsoleted. Closing until we have a new 4.x version.

**Closed by varon** 2020-11-25 20:05 UTC
