### ISSUE TITLE
Make examples viewable from web

### ISSUE THREAD

**Issue by cra0zy** [opentk/opentk#362] opened 2016-03-08 21:21 UTC
I propose that we do the following:
1) Move all the code from examples app into a separate repo and make perproject csproj files, so just one example can be downloaded
2) Move all the documentation from the examples app into the same repo, and make a website for examples out of it (with github.io thing)
3) Remove the examples app from the main repo

Why do this?

Well it seems silly for the end user to have to download full source code just to get examples with documentation... most people probably don't even know that they exist...

@amulware @wcdeich4 Thoughts?

**Comment by wcdeich4** [comment] 2016-03-09 01:45
@cra0zy by "so just one example can be downloaded" you mean they could download only the one they want, or download them all, right? 

I'm ok w/ it either way.  BTW, who pays for github.com/opentk?  I know my basic free github account can only have 2 repositories.

A little off topic, but I have been working on how to make a WinForm glControl tutorial video like I said, but had some problems w/ screen capture software on my cheap laptop + been busy @ work. I think I've found software that can run on my laptop; still bust @ work.

**Comment by leezer3** [comment] 2016-03-09 01:49
I agree in principle, but you've got to be careful.

The issue is that you require some way of getting OpenTK.dll into the Examples folder.
Currently, this can just be done with some post-build scripting, but if you separate the repositories then you need to either provide a nuget package or something.

That's fine, but not ideal, and I'm sure someone will find a way to break it immediately. At present, everything required is in one lump.

Per-project csproj files is a very good idea.

**Comment by amulware** [comment] 2016-03-09 06:01
I am not convinced this is a good idea. I do not think that the intended usage of OpenTK is to build it yourself. Instead people should download the DLL, or get the package.

I think it makes more sense to keep examples close to the code, so that if the API is changed, the examples are kept up to date with it.

**Comment by cra0zy** [comment] 2016-03-09 09:56
> @cra0zy by "so just one example can be downloaded" you mean they could download only the one they want, or download them all, right?

Yes

> I'm ok w/ it either way. BTW, who pays for github.com/opentk? I know my basic free github account can only have 2 repositories.

It should be free, as long as repos are public.

> The issue is that you require some way of getting OpenTK.dll into the Examples folder.
> Currently, this can just be done with some post-build scripting, but if you separate the repositories then you need to either provide a nuget package or something.

Good point there.

> I am not convinced this is a good idea. I do not think that the intended usage of OpenTK is to build it yourself. Instead people should download the DLL, or get the package.

I think you might have misread something, examples are placed only with the source code, instead of being available somewhere else, that's the problem I am talking about.

> I think it makes more sense to keep examples close to the code, so that if the API is changed, the examples are kept up to date with it.

Kept up to date.. haha... that's also kind of the problem. The way examples are written right now is totally broken. Output tab is not working at all, half of them don't have documentation, and some don't provide all the parts that they are using(content).

They take more then 30 secs to compile so they are useless when it comes to implementing new stuff.

Also don't even get me started on them using WinForms...

Either way a rewrite to something better is needed.

-------

About moving them to a separate repo, I thought about it and it's better to keep examples source code in this repo, and use a submodule to link them to the website repo, tho examples will still need a proper rewrite.

**Comment by amulware** [comment] 2016-03-09 16:08
>I think you might have misread something, examples are placed only with the source code, instead of being available somewhere else, that's the problem I am talking about.

Yes, I think I misunderstood. Thanks for clarifying.

---

About the submodule, I'm not sure I understand in what way you want to link things. Feel free to elaborate further, or just go ahead - I might be a bit thick today. :D

---

Regarding writing new examples, should we make a list of what features we want to cover?

I would not mind creating a few example projects, especially if I can write tutorials about them on my blog (which I tend to do). For example, I have this OpenTK-introduction project that I wrote about some time ago: https://github.com/amulware/genericgamedev-opentk-intro (link to blog post in readme)

I don't mean to appropriate the examples, or 'profit' from them in any direct way, but I write blog posts anyways, so if I can combine that with helping out OpenTK, that might be nice.

**Comment by cra0zy** [comment] 2016-03-09 16:29
> About the submodule, I'm not sure I understand in what way you want to link things. Feel free to elaborate further, or just go ahead - I might be a bit thick today. :D

Submodules are used to link whole github repos to a folder of another. See: https://github.com/mono/MonoGame/tree/develop/ThirdParty

Now the idea is to keep all the examples in this repo, but to link this repo to the web repo which will just package all the examples for the webiste. This way we can update the example in this repo as much as we want, but the website repo will get snapshots only on stable versions.

> Regarding writing new examples, should we make a list of what features we want to cover?
> 
> I would not mind creating a few example projects, especially if I can write tutorials about them on my blog (which I tend to do). For example, I have this OpenTK-introduction project that I wrote about some time ago: https://github.com/amulware/genericgamedev-opentk-intro (link to blog post in readme)
> 
> I don't mean to appropriate the examples, or 'profit' from them in any direct way, but I write blog posts anyways, so if I can combine that with helping out OpenTK, that might be nice.

All the tutorials will need to be placed within the same folders as the examples (will probably need to use either html or markup):
 1. Makes it easy to package
 2. Makes it easy to keep stuff updated for stable versions (modifications can be done to devel version while we are still displaying the stable one)
 3. Makes it easy for others to modify

**Comment by wcdeich4** [comment] 2016-03-11 00:07
Of course we want the tutorials in the example folders in source control, but I don't see any objection to @amulware having a copy of the tutorials on his blog with a link that says "Hey world, check out the new OpenTK development over at github!!!!"

**Comment by amulware** [comment] 2016-03-11 05:26
Are we really looking for 'tutorials' for the OpenTK site anyways? Or just nicely commented examples?

In either case, I agree that there is no harm done in having that duplicate content, and it will make it much easier for me to justify spending significant time on it.

**Comment by cra0zy** [comment] 2016-03-11 06:01
> Are we really looking for 'tutorials' for the OpenTK site anyways? Or just nicely commented examples?
> 
> In either case, I agree that there is no harm done in having that duplicate content, and it will make it much easier for me to justify spending significant time on it.

I am ok with you making a copy for your blog, I was just saying that they need to exist in this repo as well.

On what type of tutorials are needed on the OpenTK side, well those have to be very focused on specific features, for example, we should have: getting input, rendering basic triangle, how to embed into winforms/gtk, etc, but we should not have: collision detection, pathfinding, etc.

**Comment by amulware** [comment] 2016-03-11 10:31
Makes sense to me.

How about overlapping with general OpenGL tutorials? Should we try to be complete, or should we focus on features and specifics that are different with OpenTK?

**Comment by cryptocompress** [comment] 2017-03-09 10:36
Hello,

by chance I stumbled upon the "Examples" folder in an old repository. It would be great to have it included in this repository and linkes to it prominently in the readme.

Thanks!

**Comment by daerogami** [comment] 2017-03-12 23:03
@cryptocompress Examples were removed from the repository in #413 because they were out-of-date. The focus of this discussion (if I understand the history correctly) is where they will go once they are up-to-date.

@amulware I don't think going for completeness is necessary unless we want to provide boiler-plate code for new users. If the purpose is for verifying functionality, that should go in tests.

Focusing on distinct OpenTK features seems the most pragmatic.

**Comment by varon** [comment] 2017-06-11 18:44
Closing, as we reached a conclusion on this.

We'll need to set up an examples repository later on.

**Closed by varon** 2017-06-11 18:44 UTC
Labels: question / discussion
