### ISSUE TITLE
[4.6.0] Exception in Matrix4 type initializer on netcoreapp3.1

### ISSUE THREAD

**Issue by NoneGiven** [opentk/opentk#1257] opened 2021-03-18 20:42 UTC
### Description

When using OpenTK 4.6.0 and accessing certain members of the `Matrix4` struct on `netcoreapp3.1`, a runtime exception is thrown. `Matrix3` seems to work fine. The exception does not occur on `net5.0`.

### Repro steps

Please provide the steps required to reproduce the problem

1. Install OpenTK 4.6.0 to a console application targeting `netcoreapp3.1`

2. Execute `Matrix4 test = Matrix4.Identity;`

### Expected behavior

It works.

### Actual behavior

```
An unhandled exception of type 'System.TypeInitializationException' occurred in ConsoleApp2.dll
The type initializer for 'OpenTK.Mathematics.Matrix4' threw an exception.

1 of 2 InnerExceptions
TypeInitializationException: The type initializer for 'OpenTK.Mathematics.Vector4' threw an exception.

2 of 2 InnerExceptions
FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```

It appears to be looking for a 5.0 version of the assembly even though the target framework is 3.1, so that would explain why switching the target to 5.0 makes the issue go away.

### Related information 

* Windows 10
* OpenTK 4.6.0 from NuGet
* .NET Core 3.1

**Comment by NogginBops** [comment] 2021-03-18 21:59
It seems like the multi-targeting for the `OpenTK.Mathematics` package isn't working as it should be. 
The issue is that we switched the `OpenTK.Mathematics` project to multi-target .net core 3.1 and .net 5. What this should have done is pull and use the correct version of `System.Runtime.CompilerServices.Unsafe`. But it looks like it's looking for the .net 5 version of it instead of the 3.1 version.

Just to make sure, could you try restoring your nuget packages and trying to run again?

I'm not entirely sure why it's not working, it's most likely in how we build and or make our nuget packages that doesn't handle the multi-targeting correctly.

The workaround for now is to use OpenTK 4.5.0 or switch to .net 5. Though we want to find a fix for this.

**Comment by PJB3005** [comment] 2021-03-18 22:10
The NuGet packages aren't being built with correct multi-framework targeting apparently.

**Closed** 2021-03-19 00:29 UTC
