### ISSUE TITLE
OpenTK

### ISSUE THREAD

**Issue by Arhio** [opentk/opentk#865] opened 2018-11-22 14:29 UTC
### Description

Problem with OpenTK.GLControl

### Repro steps

Good afternoon. Please tell me what is my mistake? OpenTK and OpenTK.GLControl was installed in the project on VS2017 via NuGet. But GLControl did not appear in the Toolbox to be placed in the Form. And in the selection of elements too. You try to put OpenTK.GLControl.a dll in the .NET Framework component list throws an error that "there are no components that could be placed in this Toolbox". Tell me how to load GLControl?

### Expected behavior

I hope you will help me. And it be work.

### Actual behavior

OpenTK.GLControl not work.

### Related information 

* Windows 7
* Native backend
* NuGet OpenTK  3.0.1
* .NET Framework
* Visual Studio 2007

**Comment by Nihlus** [comment] 2018-11-22 15:36
Closing as a duplicate of #432.

**Comment by varon** [comment] 2018-11-23 07:03
Thanks for the report @Arhio.

At the moment we really have our hands full with 4.0 and moving stuff over; if you're desperate to give it a go, we'd love to see a PR to try removing the assembly signing from `OpenTK.GLControl`, which we believe might fix the issue via #859.

We're closing this, but if you have any questions feel free to ask away in #432 !

**Closed by varon** 2018-11-23 07:03 UTC

**Comment by Arhio** [comment] 2018-11-23 12:56
There are no problems. Already found a solution. Must be declared in Form.Designer string " this.glControl = new OpenTK.GLControl ();" and specify all necessary GLControl parameters. See how other controls are created. Next, you must declare "GLControl glControl;" in the Form class and enter the control initialization in the public Form() method.CreateControl (); this.Controls.Add(glControl);. Then it works. Great product you have. I like it.
