### ISSUE TITLE
wglGetProcAddress is broken

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#282] opened 2015-07-13 08:08 UTC
Reported on the forums [here](http://www.opentk.com/node/4015) and [here](http://www.opentk.com/node/4045). wglGetProcAddress is returning non-null function pointers that don't work for OpenGL 1.0 functions. We already have a work around for when wglGetProcAddress return [-1, 3] to use the standard win32 GetProcAddress, but wglGetProcAddress can also return "normal" looking function address that don't work.

> When wglGetProcAddress is called to fetch glBindTexture, 0x51CE5370 is returned. Calling this does not work.
> When GetProcAddress is called to fetch glBindTexture, 0x6BE14FA8 is returned. Calling this works.

Looks like the correct thing to do is to change our GetProcAddress to check the function name, and to always use win32 GetProcAddress for OpenGL 1.0 functions.

**Comment by WernerWenz** [comment] 2016-09-28 14:25
Technically this not a bug, but rather a feature request for a utility "GetProcAddress" func.
The issue lies within the GL1.1 implementation from MS, that is exposed via opengl32.dll.

GetProcAddress just gets the function pointer for the GL1.1 dll export
while wglGetProcAddress queries a function pointer from the driver (and thus needs an active context).

God knows, why and what exactly a given driver returns here, when a GL1.1 name is passed, but its an known issue, that they don't support this: 
For more details see https://www.opengl.org/wiki/Load_OpenGL_Functions#Windows

**Comment by varon** [comment] 2017-06-11 17:53
Closing as this relates to #291.

**Closed by varon** 2017-06-11 17:53 UTC
Labels: bug, opengl, os / win32 / desktop
