### ISSUE TITLE
Incorrect behaviour when pressing two shifts.

### ISSUE THREAD

**Issue by pdrapoport** [opentk/opentk#739] opened 2018-03-05 22:25 UTC
### Description

When both left and right shift are pressed and one of them (left, for example) is released there is no keyUp signal. So when right shift is released, left is still considered to be pressed.

### Repro steps

For example. Run in cycle something like this.
```
OpenTK.Input.KeyboardState state
if (state.IsAnyKeyDown)
{
  Keys = all_keys.Where(state.IsKeyDown);
  foreach (var k in keys)
    Debug.WriteLine(k.ToString())
}
```

### Expected behaviour

When I have both shifts pressed and then release one of them, it is expected that released shift would not be counted as pressed.

### Actual behaviour

When both Shift keys are pressed and then they are released, Shift key which was released first still counted as pressed and will still be in the Keys (in Repro section)

### Related information 

* Operating system: Win10, up-to-date
* SDL or Native backend: Not sure
* What version of OpenTK (Installer, NuGet, Source Code): Not sure
* What runtime (.NET Framework, CoreCLR, Mono): .NET Framework 4.7.0.
* Workarounds (if any)

**Comment by leezer3** [comment] 2018-03-15 20:05
Can't reproduce this on either SDL2 or the native backend, using Windows 8.1

**Comment by programmer-pixie** [comment] 2018-04-04 15:30
I would like to examine this bug.

**Comment by varon** [comment] 2020-11-25 20:01
Fixed by 4.x

**Closed by varon** 2020-11-25 20:01 UTC
Labels: bug, input, windows, windows + SDL
