### ISSUE TITLE
"Failed to load the assembly" in Rewrite.exe when trying to build

### ISSUE THREAD

**Issue by copygirl** [opentk/opentk#710] opened 2018-01-01 20:49 UTC
### Description

Build "fails" with the following error. It actually seems to continue running the tests, though when trying to use the resulting `OpenTK.dll` I get a `BindingsNotRewrittenException`.

```
Target AfterBuild:
    Executing: mono bin/Release/../../../Generator.Rewrite/bin/Release/Rewrite.exe --assembly bin/Release/OpenTK.dll --signing-key ../../OpenTK.snk
    Failed to load the assembly. It may already have been rewritten, and the debug symbols no longer match.
    System.InvalidOperationException: Operation is not valid due to the current state of the object.
        at Mono.Cecil.ModuleDefinition.ReadSymbols (Mono.Cecil.Cil.ISymbolReader reader) [0x0002f] in <2e24b151dd8041d8b7d36a855bb53c66>:0
        at Mono.Cecil.ModuleReader.ReadSymbols (Mono.Cecil.ModuleDefinition module, Mono.Cecil.ReaderParameters parameters) [0x0004a] in <2e24b151dd8041d8b7d36a855bb53c66>:0
        at Mono.Cecil.ModuleReader.CreateModule (Mono.Cecil.PE.Image image, Mono.Cecil.ReaderParameters parameters) [0x00081] in <2e24b151dd8041d8b7d36a855bb53c66>:0
        at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0000d] in <2e24b151dd8041d8b7d36a855bb53c66>:0
        at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0006c] in <2e24b151dd8041d8b7d36a855bb53c66>:0
        at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00000] in <2e24b151dd8041d8b7d36a855bb53c66>:0
        at OpenTK.Rewrite.Program.Rewrite () [0x00099] in <093950cc61144551b17c56e82fd446a2>:0
```

### Repro steps

Run `./build.sh`

### Related information 

- **Operating system:** Arch Linux
- **What runtime:** Mono `5.0.0`

**Comment by Nihlus** [comment] 2018-01-01 21:22
Try manually cleaning all build folders (bin, obj, etc) and then rebuilding.

**Comment by copygirl** [comment] 2018-01-02 00:21
I tried removing all untracked folders with no luck, then only the `bin` folder, again the same. There is no `obj` folder.

**Comment by Nihlus** [comment] 2018-01-02 00:24
That doesn't sound right. There's always an obj folder. In any case, did you remove all of the bin and obj folders from all of the projects? If that still doesn't do it, get rid of your local copy and clone the repo again. Need to be sure that it happens when working from a clean slate - I can't reproduce it locally on Mint 18.

**Comment by copygirl** [comment] 2018-01-02 00:33
Oh, in `src`!

**Comment by copygirl** [comment] 2018-01-02 00:46
Removed `bin`, `packages` etc, including projects' `bin` and `obj` folders and .. I think essentially just re-downloaded and re-built the whole thing. Same error.

**Comment by Nihlus** [comment] 2018-01-02 00:48
I got nothing. Can't reproduce. Could you try running the command manually through an IDE and debugging the rewriter? What's the state when it hits that error, etc.

**Comment by copygirl** [comment] 2018-01-02 11:43
Went ahead and installed MonoDevelop to debug this, and I can't seem to step into the `Mono.Cecil` assembly to see what's going on. What am I missing?

**Comment by ThomasD13** [comment] 2018-01-02 11:59
I've got a weird issue recently, when building opentk from source. It was my fault, some jumps between old/new branches introduced the issue I think. Did you already try to clean ala "git clean -d -x -f" your working directory? That worked at least for me.

Apart from that, I had with linux an issue, that some F# stuff was not correctly installed. That happened at the very first build attempt to me. But I can't remember exactly the error code.

**Comment by copygirl** [comment] 2018-01-02 13:56
> Apart from that, I had with linux an issue, that some F# stuff was not correctly installed. That happened at the very first build attempt to me. But I can't remember exactly the error code.

I also got an F# related error, but that was resolved once I installed [`fsharp`](https://aur.archlinux.org/packages/fsharp/).

----

Scrolling up further in the `build.sh` output log, I just noticed another error, actually:

```
Target AfterBuild:
    Executing: mono bin/Release/../../../Generator.Rewrite/bin/Release/Rewrite.exe --assembly bin/Release/OpenTK.dll --signing-key ../../OpenTK.snk
    Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
        at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) [0x000e3] in <05dd0d97f1d94bf8af79102ba271498a>:0 
        at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) [0x00007] in <05dd0d97f1d94bf8af79102ba271498a>:0 
        at OpenTK.Rewrite.Program.Rewrite () [0x0010a] in <05dd0d97f1d94bf8af79102ba271498a>:0 
				Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
        at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) [0x000e3] in <05dd0d97f1d94bf8af79102ba271498a>:0 
        at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) [0x00007] in <05dd0d97f1d94bf8af79102ba271498a>:0 
        at OpenTK.Rewrite.Program.Rewrite () [0x0010a] in <05dd0d97f1d94bf8af79102ba271498a>:0 
				Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
        at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) [0x000e3] in <05dd0d97f1d94bf8af79102ba271498a>:0 
        at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) [0x00007] in <05dd0d97f1d94bf8af79102ba271498a>:0 
        at OpenTK.Rewrite.Program.Rewrite () [0x0010a] in <05dd0d97f1d94bf8af79102ba271498a>:0 
```

Do I need to build OpenTK in minimal mode, or ..?

**Comment by Frassle** [comment] 2018-01-02 14:07
It couldn't resolve System.Drawing. That's a new one. Could you dump the full recursive contents (using something like tree) of your lib/mono directory (Probably /usr/local/lib/mono)?

Might be that System.Drawing isn't installed in the 2.0 folders but only in the 2.0-api folders. I'd thought it was just mscorlib we'd have to worry about for that.

**Comment by copygirl** [comment] 2018-01-02 14:22
Additionally, in MonoDevelop, it's showing other things it can't resolve:

- `System`
- `System.Data`
- `System.Drawing`
- `System.Xml`

And [here is the directory tree of `/lib/mono`](https://gist.github.com/copygirl/42c83a409a942eefe181c6f00ae89227).

**Comment by VPeruS** [comment] 2018-01-02 14:27
Try to `run msbuild OpenTK.csproj /v:diag` it may contain some additional information

**Comment by copygirl** [comment] 2018-01-02 14:43
[Here](https://gist.github.com/copygirl/6fba2965af7552cfbb779e5b65dd2743) is the output of `xbuild OpenTK.csprog /v:diag`.
Unsure if msbuild is required. I tried installing one, possible even two of the `msbuild` packages from the [AUR](https://aur.archlinux.org/packages/?O=0&K=msbuild) with various errors. Let me know if it is and I'll try digging into that more.

**Comment by Frassle** [comment] 2018-01-02 14:50
I don't think this is an msbuild problem. This is an issue with Mono.Cecil resolving assembly names, given @Nihlus can't repro I'd guess something specific about how you've installed mono. I'll try and put together a simple cecil only program to run to see if it can point the issue out.

**Comment by Nihlus** [comment] 2018-01-02 20:06
It could be related to the way the AUR installs mono, but I'm not sure. This is Mono 5.0.0, right? I'm using Mono 5.4.1.6, so that may also be a factor.

**Comment by Frassle** [comment] 2018-01-02 21:44
@Nihlus Did you install via AUR or some other way?

**Comment by Nihlus** [comment] 2018-01-02 21:45
I used the official Mono repositories for Ubuntu/Debian.

**Comment by VPeruS** [comment] 2018-01-02 21:48
I installed mono-stable and msbuild-bin from AUR multiply times and all them work without problems

**Comment by copygirl** [comment] 2018-01-03 00:29
I was using the `mono` package from the official repositories. Removed that and got myself `mono-stable` and `msbuild-bin`.

The situation in MonoDevelop doesn't appear to change (could not locate assemblies `System` etc). Calling `./build.sh` fails much earlier now with: [`The default XML namespace of the project must be the MSBuild XML namespace.`](https://gist.github.com/copygirl/25321befae6f9859e86c4f1ee935692f)

**Comment by VPeruS** [comment] 2018-01-05 12:32
Got exectly same error. It didn't occur because previously xbuild was used as compiler or you build before merge conditional stylecops props. Add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to Project in build/StyleCop.props

**Comment by copygirl** [comment] 2018-01-05 15:01
Can confirm @VPeruS's findings. The change to `StyleCops.props` allows me to use `msbuild`, but it fails with similar errors:

```
AfterBuild:
  mono bin/Release/../../../Generator.Rewrite/bin/Release/Rewrite.exe --assembly bin/Release/OpenTK.dll --signing-key ../../OpenTK.snk
  Debugging symbols for target assembly not found.
  Please make sure that debugging symbols are being generated.
  Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) [0x00103] in <b36b868e93a8406199bc7b03e5743008>:0
    at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) [0x00007] in <b36b868e93a8406199bc7b03e5743008>:0
    at OpenTK.Rewrite.Program.Rewrite () [0x00126] in <b36b868e93a8406199bc7b03e5743008>:0
  Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) [0x00103] in <b36b868e93a8406199bc7b03e5743008>:0
    at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) [0x00007] in <b36b868e93a8406199bc7b03e5743008>:0
    at OpenTK.Rewrite.Program.Rewrite () [0x00126] in <b36b868e93a8406199bc7b03e5743008>:0
  Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) [0x00103] in <b36b868e93a8406199bc7b03e5743008>:0
    at OpenTK.Rewrite.OpenTKAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) [0x00007] in <b36b868e93a8406199bc7b03e5743008>:0
    at OpenTK.Rewrite.Program.Rewrite () [0x00126] in <b36b868e93a8406199bc7b03e5743008>:0
```

**Comment by Nihlus** [comment] 2018-01-05 17:02
I saw it too, now, after manually cleaning the solution of `bin` and `obj` folders. I deleted the entire local clone and recloned it, still happens. Weird. Can start debugging it now at least.

**Comment by Frassle** [comment] 2018-01-05 17:04
Sorry I've been busy with work and toddlers. I'll try and write up a branch of OpenTK tonight that will dump all the assembly resolution steps to the console. Once I've posted that you should be able to download and try and build it, paste the console log back here and hopefully we can work out why resolution is failing.

**Comment by Nihlus** [comment] 2018-01-05 17:15
Did some debugging. It's only ever searching the 4.5 API folder, not the 2.0-api folder where the real assembly is.

**Comment by Frassle** [comment] 2018-01-05 21:54
Odd I thought the new resolver was a copy of the code of the old resolver but with an extra check in "-api" for mscorlib. I'll see if I can work out what's changed and push a new resolver up to look in "-api".

**Comment by Nihlus** [comment] 2018-01-05 21:59
Check that it's actually the resolver that's the issue first, I'd say. Remove it, build, and see if the issue persists.

**Comment by Frassle** [comment] 2018-01-05 22:01
Could you try that, I don't have an already setup arch install?

**Comment by Nihlus** [comment] 2018-01-05 22:12
The issue is present on both Mac & Linux, but I'll give it a go and see what I can find out. Apparently, it's not present on Windows - the Appveyor build shows no signs of it.

**Comment by Nihlus** [comment] 2018-01-05 22:43
I can confirm that the default assembly resolver does not have this issue.

**Comment by copygirl** [comment] 2018-01-05 23:36
For another project I compile using `dotnet`, I have to specify the `FrameworkPathOverride` enviroment variable, in my case to `"/lib/mono/4.5/"`. It's actually a [tracked issue on dotnet](https://github.com/dotnet/sdk/issues/335#issuecomment-322137207) right now. Not sure if this is related to this or not. I should give it a try. .... huh.

Using `4.5` makes them resolve properly, but:
```
mono bin/Release/../../../Generator.Rewrite/bin/Release/Rewrite.exe --assembly bin/Release/OpenTK.dll --signing-key ../../OpenTK.snk
  Debugging symbols for target assembly not found.
  Please make sure that debugging symbols are being generated.
```
Using `2.0-api`, compiling fails:
```
  /usr/lib/mono/4.5/mcs.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:anycpu32bitpreferred /warn:4 /doc:bin/Release/Bind.xml /baseaddress:285212672 /define:TRACE /highentropyva+ /reference:/lib/mono/2.0-api/mscorlib.dll /reference:/lib/mono/2.0-api/System.Core.dll /reference:/lib/mono/2.0-api/System.dll /reference:/lib/mono/2.0-api/System.Xml.dll /reference:/lib/mono/2.0-api/System.Xml.Linq.dll /debug- /filealign:4096 /keyfile:../../OpenTK.snk /optimize+ /deterministic+ /out:obj/Release/Bind.exe /ruleset:../../stylecop.ruleset /subsystemversion:6.00 /target:exe /utf8output /analyzer:../../packages/StyleCop.Analyzers/analyzers/dotnet/cs/StyleCop.Analyzers.CodeFixes.dll /analyzer:../../packages/StyleCop.Analyzers/analyzers/dotnet/cs/StyleCop.Analyzers.dll CSharpSpecWriter.cs FuncProcessor.cs GL2/GL4Generator.cs IBind.cs Main.cs DocProcessor.cs Settings.cs BindStreamWriter.cs EnumProcessor.cs Utilities.cs ISpecReader.cs Properties/AssemblyInfo.cs CL/CLGenerator.cs GL2/Generator.cs Structures/Type.cs Structures/Function.cs Structures/Constant.cs Structures/Enum.cs Structures/Delegate.cs Structures/Parameter.cs Structures/FlowDirection.cs ES/ESGenerator.cs XmlSpecReader.cs ES/ES2Generator.cs ES/ES3Generator.cs GL2/GL2Generator.cs Structures/Documentation.cs ES/ES31Generator.cs "/tmp/.NETFramework,Version=v4.6.1.AssemblyAttributes.cs"
/tmp/.NETFramework,Version=v4.6.1.AssemblyAttributes.cs(4,46): error CS0234: The type or namespace name `TargetFrameworkAttribute' does not exist in the namespace `System.Runtime.Versioning'. Are you missing an assembly reference? [/home/copygirl/projects/opentk/src/Generator.Bind/Generator.Bind.csproj]
CSharpSpecWriter.cs(730,34): error CS1502: The best overloaded method match for `string.Join(string, string[])' has some invalid arguments [/home/copygirl/projects/opentk/src/Generator.Bind/Generator.Bind.csproj]
  /lib/mono/2.0-api/mscorlib.dll (Location of the symbol related to previous error)
CSharpSpecWriter.cs(730,45): error CS1503: Argument `#2' cannot convert `System.Collections.Generic.List<string>' expression to type `string[]' [/home/copygirl/projects/opentk/src/Generator.Bind/Generator.Bind.csproj]
```
Hope this helps cracking down on the issue somehow.

**Comment by Nihlus** [comment] 2018-01-05 23:39
The first issue does make sense - there aren't any debugging symbols in Release mode.

**Comment by copygirl** [comment] 2018-01-05 23:47
This is just from calling `./build.sh`. Is this the intended behavior?

**Comment by Nihlus** [comment] 2018-01-05 23:47
Yes.

**Comment by copygirl** [comment] 2018-01-05 23:55
So `Rewrite.exe` is being called if `build.sh` builds OpenTK in Release mode..? Do I then **have** to re-build in an IDE using Debug mode? If it doesn't build in Release mode (can it, ever?), why isn't that the default when building..? I suppose I'm missing or misunderstanding something here.

**Comment by Frassle** [comment] 2018-01-06 13:01
I've pushed a changeset to https://github.com/Frassle/opentk/tree/cecil to print all the resolve steps. Might give a hint as to where it is/isn't looking.

Example from running on my windows machine:
```
         ==========================================================================================
         Resolve(System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
         directories = System.Collections.Generic.List`1[System.String]
         SearchDirectory(System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, System.Collections.Generic.List`1[System.String])
             .\System.Drawing.exe does not exist
             .\System.Drawing.dll does not exist
             bin\System.Drawing.exe does not exist
             bin\System.Drawing.dll does not exist
             Return null
         framework_dirs = C:\Windows\Microsoft.NET\Framework\v4.0.30319
         GetAssemblyInGac(System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
             gac_paths = C:\Windows\assembly, C:\Windows\Microsoft.NET\assembly
             GetAssemblyInNetGac(System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
                 C:\Windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll exists
                 Return System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

**Comment by Nihlus** [comment] 2018-01-06 13:40
Here's from Linux Mint 18, with Mono 5.4.6.1 and .NET Core 2.1.3.

**Comment by VPeruS** [comment] 2018-01-06 17:13
Clear version of Cecil also throw same error. Even I have System.Drawing.dll in /usr/lib/mono/4.5 but it is link to gac 4.0.0.0 version

**Comment by Frassle** [comment] 2018-01-06 20:56
Yeh ok kinda makes sense, it can't find it in the gac (because mono doesn't ship old frameworks anymore except for the api compiler modules) and in /usr/lib/mono it's just looking in the 4.5 folder which doesn't match version 2 we're asking for.

But how the hell does the standard cecil resolver find it? As far as I can tell I copied the code exactly the same except for when looking for mscorlib.

**Comment by VPeruS** [comment] 2018-01-06 21:13
It don't resolve it.

**Comment by VPeruS** [comment] 2018-01-06 21:30
It may be because Cecil by default use https://github.com/jbevain/cecil/blob/7aea484589dc60535e23f7799743e697898352ae/Mono.Cecil/ModuleDefinition.cs#L394 not BaseAssemblyResolver

**Comment by Frassle** [comment] 2018-01-07 10:30
The only thing [DefaultAssemblyResolver](https://github.com/jbevain/cecil/blob/7aea484589dc60535e23f7799743e697898352ae/Mono.Cecil/DefaultAssemblyResolver.cs) adds over BaseAssemblyResolver is a cache. Lookups are unchanged.

**Comment by Nihlus** [comment] 2018-01-09 11:13
We do seem to be using an older version of Cecil than the master branch (0.10.0-beta6). Perhaps something changed in the interim?

**Comment by Frassle** [comment] 2018-01-09 11:58
So remove our resolver, update cecil to latest and see how that goes?

**Comment by Nihlus** [comment] 2018-01-14 17:26
@Frassle Any more ideas on this?

**Comment by VPeruS** [comment] 2018-01-14 18:55
I suppose changing https://github.com/opentk/opentk/blob/develop/src/Generator.Rewrite/OpenTKAssemblyResolver.cs#L54 to use path /usr/lib/mono/2.0-api instead of /usr/lib/mono/4.0 can fix it. Also on plaform only with 2.0 runtime(because typeof(object)) it will resolve everthing to without problem(didn't test). Suggest fix to disscuss - broke loop when mscorlib is found (here https://github.com/opentk/opentk/blob/develop/src/Generator.Rewrite/Program.cs#L113)

**Comment by Frassle** [comment] 2018-01-14 19:00
Let me disassemble our cecil version. I'll try and rewrite the resolver to match + our 2.0 fix. Will push a branch later.

**Comment by Nihlus** [comment] 2018-01-14 22:19
Hopefully we should have killed this issue for good now :P

**Closed** 2018-01-14 22:18 UTC
Labels: binding generator, bug
