### ISSUE TITLE
[NuGet] GLControl doesn't add to VS2012 Toolbox when installed via NuGet

### ISSUE THREAD

**Issue by david-bakin** [opentk/opentk#37] opened 2014-01-08 14:22 UTC
This issue was originally reported [here](http://www.opentk.com/node/3513), and repro'd by [the Fiddler](http://www.opentk.com/user/1) who believes it happens with NuGet installed OpenTk but not manual installed OpenTk:

I can't get GLControl to appear in the VS2012 toolbox - I'm trying the OpenTK "Building a Windows.Forms + GLControl based application" tutorial.

I have: VS2012. A new Windows Forms project. OpenTK 1.1.1456.5398 and OpenTK.GLControl 1.1.1456.5398 installed in my solution via NuGet. They show up in the project references.

When I use the "choose items" dialog in the toolbox, and find the dll OpenTK.GLControl.dll it eventually tells me:

```
---------------------------
 Microsoft Visual Studio
 ---------------------------
 There are no components in 'R:\...\OpenGLTest1\packages\OpenTK.GLControl.1.1.1456.5398\lib\NET40\OpenTK.GLControl.dll' that can be placed on the toolbox.
 ---------------------------
```

Various online solutions to that are proposed (not specific to GLControl) - including drag/drop of the DLL right onto the toolbox (also doesn't do anything), restarted VS completely (doesn't help), compiling the project first then restarting VS (doesn't help).

[The Fiddler](http://www.opentk.com/user/1) says: 

> I can reproduce this in VS2013 when using the nuget package. If I uninstall the nuget package and reference OpenTK.dll and OpenTK.GLControl.dll directly from a local installation, then it appears to be working correctly.

**Comment by sureshjoshi** [comment] 2015-02-26 17:12
Is there any update on this bug? I'm not able to add the GLControl to my Toolbox with the same error as the OP. 

Using 1.1.1589.5942 and Visual Studio 2013

**Comment by sergey-miryanov** [comment] 2015-06-03 13:57
@sureshjoshi Try to install OpenTK.GLControl from NuGet

**Comment by jddde** [comment] 2016-04-18 09:28
Hello,
I use:
- MS VS 2015 14.0.25123.00 update 2
- .net Framework 4.6.01038
I have created a windows Forms project and installed from nuget:
- OpenTK.GLControl 1.1.2225 version 1.1.1589.5942
I do what is described here :http://www.opentk.com/doc/chapter/2/glcontrol (Building a Windows.Forms + GLControl based application)

but I can't find neither OpenTK.GLControl.dll nor GLControl in the "Choose Toolbox items" window.

How can I do ?
![toolboxitems](https://cloud.githubusercontent.com/assets/18527288/14599626/b623ae5a-0558-11e6-8bfd-e3008ea24648.png)

**Comment by jddde** [comment] 2016-04-18 09:42
OK, I found the OpenTK.GLControl.dll but I get the message "There are no components in .. that can be placed on the toolbox."
That is strange...
![nocomponents](https://cloud.githubusercontent.com/assets/18527288/14599945/8ef0f020-055a-11e6-956e-5fbe67aa2e30.png)

**Comment by jddde** [comment] 2016-05-17 14:35
I tried what david-bakin commented on 9 Jan 2014 : I added manually the control in Form1.designer.cs file but that makes VS2015 crash when I open Form1 in design mode.
Here is the code:
`{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.gLControl = new OpenTK.GLControl();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(16, 19);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(35, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "label1";
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(284, 261);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.gLControl);
            this.Name = "Form1";
            this.Text = "Form1";
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label label1;
        private OpenTK.GLControl gLControl;
    }
}`

**Comment by wcdeich4** [comment] 2016-05-17 21:29
An issue has long existed that you will probably need to download the .dll from github instead of using the nuget package.  If you search hard enough, there was a comment a long time ago, but I understand there are 1000s of comments....

**Comment by jddde** [comment] 2016-05-17 21:41
Thank you very much for your comment. I Will try this tomorrow.

**Comment by wcdeich4** [comment] 2016-06-07 20:53
@varon are you using Visual Studio? Someone should test i the new glControl NuGet package adds to the Visual Studio tool box as described in the tutorial:   http://www.opentk.com/doc/chapter/2/glcontrol?page=3

**Comment by varon** [comment] 2016-06-07 20:58
@jddde, you're on the right track. For the compile errors, check you've run NuGet restore. It should bring in the needed packages.

We're also working on simplifying the build process for the next release, which should help contributors.

@wcdeich4, yeah, but I've never used the GLControl package. Need me to test that?

**Comment by jddde** [comment] 2016-06-07 21:38
@wcdeich4 @varon
Well, since my post in may, I compiled with success opentk 2.0 found on this github.
I could add opengl control to the vs2015 toolbox with no issue.
I could add an opengl control on an xamarin.forms content page and on a winforms with success.
Afterwards, I shifted to https://github.com/opentk/opentk/issues/395
as I don't know how to use point sprites with opentk.
There are so few documentation!

**Comment by wcdeich4** [comment] 2016-06-08 04:07
@varon Maybe I could find time to test it on Saturday.  I can confirm that before  OpenTK.Next.GLControl 1.2.2336.6514-pre, using the NuGet package did not add to the toolbox properly, but compiling the .dll myself did work.

**Comment by wcdeich4** [comment] 2016-06-12 22:42
Doesn't seem to be working. Following  http://www.opentk.com/doc/chapter/2/glcontrol   I Right clicked in some empty space of the Toolbox, picked "Choose Items..." and browsed for OpenTK.GLControl.dll

I got the message, "There are not components in ...OpenTK.Next.GLControl.1.2.2336.6514-pre\lib\net20\OpenTK.GLControl.dll that can be placed in the toolbox."

**Comment by wcdeich4** [comment] 2016-06-12 22:43
BTW, this is the same issue as https://github.com/opentk/opentk/issues/371#issuecomment-221730858 & https://github.com/opentk/opentk/issues/371#event-672483578

**Comment by varon** [comment] 2016-06-13 07:12
@wcdeich4 Do we know if this affects the pre-release package?

**Comment by krgiddings** [comment] 2016-06-18 09:28
@varon I commented in gitter that using nuget to install the .Next packages didn't allow me to add the glcontrol to the toolbox.  Building the dll from the distribution works fine,  so something seems to be awry in the packages.

**Comment by wcdeich4** [comment] 2016-06-18 20:24
I've never been involved w/ building NuGet packages before, but since the old NuGet package & the new one also have this problem - could there be something w/ the process of building it for NuGet & downloading it thru NuGet that prevents Visual Studio from considering it contain "components" for the toolbox?

**Comment by varon** [comment] 2016-06-19 09:59
@krgiddings Thanks for the info.

So the situation seems to be that `OpenTK.GLControl` doesn't seem work in *any* NuGet package.

It seems unlikely that it would be a NuGet specific bug, but perhaps VS versions or some build setting for the package? @wcdeich4 - it's probably worth experimenting further if you've got the time. I'd try these steps:

1. Build the DLL manually and check it's working.
2. Build a NuGet package locally and check if it's working.
3. Check for differences between DLL/Local Nuget/OpenTK.Next NuGet.

I'm not using GLControl myself, so I'm pretty unfamiliar with that part of the system.  @amulware @thefiddler - Anyone got any ideas on this?

**Comment by wcdeich4** [comment] 2016-06-19 19:57
@varon the last time I built the .dll locally, it added to the toolbox & compiled, but did not run properly. That laptop has VS 2013 Community

**Comment by githubjanson** [comment] 2016-08-11 12:42
Guys,

Is there a solution for this anytime soon? I would like to use the NuGet package in VS 2015, and it's not working with the latest release 1.1.2349.61993 either.

**Comment by varon** [comment] 2016-08-11 12:46
@githubjanson Thanks for checking in.

The current solution seems to be building from source, as for some reason the NuGet build isn't working at all.

**Comment by opcon** [comment] 2016-08-25 01:24
I took a look into this and found that I couldn't add the GLControl to toolbox even when building from source. Recreating the OpenTK.GLControl project and copying all the source files fixed this. The new `OpenTK.GLControl.csproj` is changed quite a bit from the old `OpenTK.GLControl.csproj`, so I can't easily tell which part was causing the issue.

**Comment by varon** [comment] 2016-08-25 07:33
@opcon If you've got a working fix, we'd love to see a PR for it. I've got no problem if we need to re-create the project.

**Comment by opcon** [comment] 2016-08-25 07:40
Sounds good, I'll double check that nothing is broken, and that it'll work straight from a NuGet package, then I'll submit a PR.

**Comment by varon** [comment] 2016-08-25 07:50
Awesome! Thanks!

**Comment by billypilgrim-uk** [comment] 2016-10-30 14:16
anyone have a solution for this yet? i'm still unable to add the component to the toolbox when using the NuGet package (VS2015, OpenTK v2.0.0, OpenTK.GLControl v1.1.2349.61993).

i'm bundling my source code for other people and i'd prefer not to have to make them build OpenTK from source in order to compile my code if at all possible.

**Comment by wcdeich4** [comment] 2016-10-30 22:44
@billypilgrim-uk - are you able to get the glControl to actually work when you compiled it locally?  Compiling it locally, I was able get the glControl to add to the toolbox in Visual Studio 2013, but even though it compiled & the code looked good, it did not really work.  I have not tried yet in VS 2015. Strangely, projects made way back in Visual Studio 2010 & upgraded to the newer version do seem to work correctly............

**Comment by billypilgrim-uk** [comment] 2016-10-30 23:32
I actually did get it to compile and it mostly seems to be working. I 
found that the pre-release packages on NuGet also seem to work so I 
switched to those. It seems relatively ok to me but then I'm relatively 
new to OpenGL....

**Comment by wcdeich4** [comment] 2016-10-31 01:47
Um, just to be clear, when I said, "it did not really work" I meant after I added the glControl to the Toolbox & compiled & ran the code, I got a black screen.  If it's working better now, that's great.

**Comment by flagshang** [comment] 2017-03-28 08:19
I use vs2017, I have the same error that can`t load GLcontrol into vs toolbox.

**Comment by TrueNoob** [comment] 2017-04-22 12:50
VS2017 dll have not components for installing.

**Comment by ManojlovicMilos** [comment] 2017-05-04 10:46
I second that. VS2017, same problem.

**Comment by TrueNoob** [comment] 2017-05-04 20:04
Now I can install, but I can't drag & drop element to form (Install OpenTK, after GLControl)
Install GLControl and OpenTK next I got exception PlatformNotSupported

**Comment by varon** [comment] 2017-06-11 23:40
I'm going to close this, not because it's fixed, but because we're consolidating into a single issue: #432

**Closed by varon** 2017-06-11 23:40 UTC
