### ISSUE TITLE
OpenTK.Input crash with 3Dconnexion SpaceMouse Enterprise

### ISSUE THREAD

**Issue by winterhell** [opentk/opentk#639] opened 2017-08-22 14:48 UTC
When you have the SpaceMouse plugged in the PC, and you try to read with OpenTK either the keyboard, mouse or gamepad, the program crashes. If I dont use any Input functionality, it doesnt crash.
If I unplug the device the program runs but if I plug it back it crashes. I have its latest drivers 
Running on Native backend, Windows 10
OpenTK 1.1.4, 2.0 and current git version
.Net Framework 2.0 and 4.0

Is there a way to ignore the device somewhat, so the other input works?
https://www.3dconnexion.eu/index.php?id=432&redirect2=www.3dconnexion.eu

**Comment by Nihlus** [comment] 2017-08-22 14:52
There is no way of excluding single devices, so we'll just have to find the issue and fix it. Please provide the stack trace and exception message, if there is one. If possible, the relevant source file wouldn't be bad either.

**Comment by winterhell** [comment] 2017-08-22 16:10
This is what I get, maybe I need a debug version of OpenTK?
![unknown 2](https://user-images.githubusercontent.com/9436315/29575571-90edb4b2-876d-11e7-846e-b725e9c55fec.png)

**Comment by subchannel13** [comment] 2017-08-22 17:57
https://msdn.microsoft.com/en-us/library/dn457346.aspx
Can this help? Disabling "Just My Code" should help with seeing stacktrace of framework and OpenTK methods but it also mentions there is "Show External Code" in context menu in call stack.

**Comment by UnknownShadow200** [comment] 2017-08-23 22:39
Just putting a simple Console.WriteLine(button) or System.Diagnostics.Debug.WriteLine(button) in JoyStick.SetButton should do the trick

**Comment by varon** [comment] 2017-08-24 18:27
If you guys can send me one, I'll be happy to get this working :)

**Comment by winterhell** [comment] 2017-08-24 21:15
Here is what the guy got when trying it
[spaceMouseLog.txt](https://github.com/opentk/opentk/files/1250266/spaceMouseLog.txt)

**Comment by leezer3** [comment] 2017-08-25 23:00
That's very possible; I'd suspect one of the buttons is probably acting as a modifier button.

IIRC there was some discussion of this specific device in one of the PRs relating to button / axis limits, but without it to debug, it's very hard to fix this.

My initial thought would be that it *ought* to be skipped by default if the HID data descriptor reports a max number of buttons / axis above what we support:
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinRawJoystick.cs#L526

This therefore suggests to me that it's HID data packets are reporting a different number of buttons to that of the capabilities, and that their driver is probably actually handling this internally somewhere.

Can you explain how that log was generated, specifically what you're doing to get & enumerate the button numbers?
It'd also be interesting to see the output from __OpenTK.Input.Joystick.GetCapabilities()__ (or whether this crashes)
This would tell us whether the check I've linked above is failing / being skipped somewhere.

**Comment by winterhell** [comment] 2017-08-26 06:18
How the log was generated- In OpenTK\Input\JoyStickState.cs I put 
` internal void SetButton(int button, bool value)
        {
            System.Diagnostics.Debug.WriteLine(button);
            if (button < 0 || button >= MaxButtons)`
I'll check the rest when the guy with the SpaceRat comes online.

**Comment by leezer3** [comment] 2017-08-26 07:25
Ok, so that means our check at line 526 above would appear to be failing.

I'll try dropping the button limit in a test build and seeing if I can figure out why that check fails, probably tomorrow or monday.
Might not get anywhere, but its a start.

Setting a return statement in the setbutton \ getbuttons function if we are over the max buttons would probably mask this too, but thsts a horrible kludge.

**Comment by winterhell** [comment] 2017-08-26 09:43
Currently the buttons are stored in an long int with max of 64 bits, so you might need to convert that to an array.

**Comment by leezer3** [comment] 2017-08-26 09:46
That was discussed in the PR that raised the limit: The array idea adds overheads, for dubious benefit. (This is the only device so far that breaches the limit I'm aware of)

**Comment by UnknownShadow200** [comment] 2017-08-26 12:38
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinRawJoystick.cs#L624

and 

https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinRawJoystick.cs#L637

are where the setting of buttons are done - add some Console.WriteLine there perhaps? (Particularly for Range.UsageMin and Range.UsageMax)

**Comment by winterhell** [comment] 2017-08-26 13:48
[output.txt](https://github.com/opentk/opentk/files/1253694/output.txt)
The one with min:1 and max:10 is an xbox 360 gamepad. Only those lines disappear if I try it without them.
31 is the correct amount of keys the device has.
This is where I put the Console.WriteLine
[write line.txt](https://github.com/opentk/opentk/files/1253697/write.line.txt)

**Comment by leezer3** [comment] 2017-08-26 19:52
Hmm, looking at your output, I'd say that the cause of the crash is here:
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinRawJoystick.cs#L624

Your device is reporting a HID page usage with a minimum of zero, and a maximum of 255, which we would appear to be interpreting as 256 buttons. We then crash when we attempt to enumerate beyond the limit of 64.

A relatively quick and hacky fix for this crash would likely be to change the following:
```
usage <= stick.ButtonCaps[i].Range.UsageMax
```
to
```
usage <= stick.ButtonCaps[i].Range.UsageMin + JoystickState.MaxButtons
```
Would also need an appropriate error adding for above the max number of buttons, but a Debug.Print would probably be OK for this rather than throwing a hard exception.

I'm by no means sure that would actually get the thing working correctly though, as I'd strongly suspect that we're misinterpreting some custom HID data designed to be read by their own drivers.

**Comment by winterhell** [comment] 2017-08-27 14:30
[new_2 (1).txt](https://github.com/opentk/opentk/files/1254452/new_2.1.txt)
"Analyzing button collection 1 range " followed by enough buttons to overflow the 64-button limit.
It probably should be only a single collection, not two. 
For example an Xbox 360 controller shows only a single collection.
#640 also detects 2 ranges, but each range have only half the buttons.Perhaps they are multiplexed.

**Comment by leezer3** [comment] 2017-08-28 10:42
Just been skimming the SDK for the SpaceMouse, and it appears to be sending out a couple of types of different HID events:

(The Windows SDK is pretty much useless for our purposes, as it seems to be just registering a DirectInput device handle, rather than describing the events, so these are back-fudged from the Linux SDK)

### Input Events
* int[7] __data__
* int __buttons__

Presumably, the data array contains the positions of each of the axis, and the Buttons int contains the button states.

### Translate Events
* int __Type__
* int __Button__
* double __Data[6]__
* int __Period__

This appears to check the button pressed and the type, and then apply rotation matricies to the other axis. 

This really needs someone with a device, and who is better with low-level drivers than me. I can interpret the basic data structures, but exactly what's going on is unclear to me.
Further, I suspect that the Windows HID backend is not likely to ever play nicely with this device without considerable modification. 

At the minute, I'd be tempted to try and completely blacklist the device. I think we could probably do this by checking the VID & PID (We read these when assigning the GUID, so return __null__ here & check this in the candidate function https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinRawJoystick.cs#L273 ???)

**Comment by winterhell** [comment] 2017-08-29 13:37
`  if (device.GetGuid().ToString().StartsWith("0008f000-0000-0000-0000-504944564944") || device.GetGuid().ToString().StartsWith("c31c046d-0000-0000-0000-504944564944") continue;`
I put this before 'if (!QueryDeviceCaps(device) && !is_xinput)' and now the device doesnt crash the program.

**Comment by varon** [comment] 2020-11-25 20:01
Fixed by 4.x

**Closed by varon** 2020-11-25 20:01 UTC
Labels: bug, input, needs verification
