### ISSUE TITLE
Macbook pro mouse updates with an external mouse

### ISSUE THREAD

**Issue by Phyyl** [opentk/opentk#456] opened 2016-11-23 16:13 UTC
### Description

Moving the mouse with an external mouse (multiple mice) on a macbook pro while the cursor is hidden in the window yields no mouse position updates.

### Repro steps

Create an empty window, and output the mouse position in console using `Console.WriteLine(Mouse.GetState().X + ", " + Mouse.GetState().Y)`.

When the cursor is visible, there's no issue. Try setting `window.CursorVisible = false` and then move the external mouse. No movement detected!

### Expected behavior

The mouse position should move, but not if the mouse cursor is hidden in the window.

### Actual behavior

When the cursor is hidden, the mouse position stays the same.

### Related information 

* Operating system: macOS 10.11.6
* SDL or Native backend: Native
* What version of OpenTK (Installer, NuGet, Source Code): 2.0.0
* What runtime (.NET Framework, CoreCLR, Mono): Mono

**Comment by varon** [comment] 2016-11-25 17:33
Thanks for the report.

Honestly, I'm not sure of intended behaviour.

Can you post some minimal reproduction code so I can confirm how it works on Windows?

**Comment by Phyyl** [comment] 2016-11-25 17:47
There's no issue on Windows, at least not that I'm aware of. In mac, if the cursor is hidden in the window, there's no cursor movement reported by `Mouse.GetState()` OR `Mouse.GetCursorState()`.  I can't make an FPS-like camera in macOS basically. Does that clarify?

**Comment by varon** [comment] 2016-11-25 18:01
So, to confirm `Mouse.GetState()` reports movement under Windows, but not under OSX (macOS)?

**Comment by Phyyl** [comment] 2016-11-25 18:13
Exactly.

**Comment by Phyyl** [comment] 2016-11-30 18:29
I looked at how MonoGame does this part. I noticed they create a 1x1 clear pixel for the cursor when it's hidden. I can't find anything in OpenTK relating to this, perhaps the clear 1x1 pixel would be a better method? Here's their implementation of [ResetCursorRects].(https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/MacOS/GameWindow.cs#L487)

**Comment by varon** [comment] 2016-12-02 14:59
In the absence of a fix, it's probably a decent workaround.

**Comment by varon** [comment] 2016-12-12 08:11
Can we close this issue?

**Closed** 2017-06-11 21:04 UTC
