### ISSUE TITLE
Line width doesn't work

### ISSUE THREAD

**Issue by DimaS86** [opentk/opentk#956] opened 2019-09-07 08:45 UTC
Hi! In the newest version 3.1.0 in NuGet package, there is an issue with GL.LineWidth function. It seems that this function doesn't work properly. There is no way to draw a line with a defined width.
In 3.0.1 version this function worked properly.

**Comment by jvbsl** [comment] 2019-09-07 11:08
Nothing changed in the implementation of these methods.
Do you have a simple example project in which one can exchange the two versions from nuget and it shows the effect?

**Comment by k0dek0mmand0** [comment] 2019-12-04 15:24
I can confirm this. It looks to me like the float parameter is not passed correctly.

Both `GL.LineWidth( 10.0f );` and `GL.LineWidth( 5.0f );` produce exactly the same error message, including the 0x60000000 constant.

```
DebugSourceApi DebugTypeError DebugSeverityHigh 
Using glLineWidth in a Core context with parameter <width> and value '0x60000000' which was removed from Core OpenGL (GL_INVALID_VALUE)
```

**Comment by NogginBops** [comment] 2019-12-04 16:24
What version of openGL are you using and what GraphicsContextFlags are you using? Because #790 fixed a problem when creating contexts so that the correct flags are set. This might affect what the driver thinks is legal for a specific context. Especially since line thickness is optional and up to the implementation you might be getting different results. You could also read:
```c
GLint range[2];
glGetIntegerv(GL_ALIASED_LINE_WIDTH_RANGE, range);
glGetIntegerv(GL_SMOOTH_LINE_WIDTH_RANGE, range);
```
and see what values your current driver supports where ``range[0]` is the min width and `range[1]` is the max width.

**Comment by k0dek0mmand0** [comment] 2019-12-04 17:46
I'm using a forward-compatible context. The problem doesn't exist with compatibility profile.
Context creation flags are `(ForwardCompatible | Debug)`
Debug or no debug flag makes no difference.
Minor version selection (4.*) also makes no difference. I'm generally using `4.6`.
Width ranges are `1-128` for aliased and `1-63` @ `0.125` granularity for smoothed, so values `5.0f` and `10.0f` should be OK.
I've noticed that the constant `0x60000000` from the error message above is sometimes `0x0`. Doesn't change and doesn't resemble the float I specify as parameter.
This isn't a showstopper for me, just wanted to mention I also encountered this behavior.

```
AMD Radeon (TM) R7 370 Series Graphics
OpenGL 4.6.13572 Core Profile Forward-Compatible/Debug Context 19.11.3 26.20.13031.18002
GLSL 4.60
Index: 11, Color: 32 (8888), Depth: 24, Stencil: 8, Samples: 0, Accum: 0 (0000), Buffers: 2, Stereo: False
```

**Comment by jvbsl** [comment] 2019-12-04 19:57
Well ForwardCompatible means that everything marked as deprecated will not be available from your context. It seems that LineWidth != 1 was somewhat deprecated.

**Comment by k0dek0mmand0** [comment] 2019-12-04 20:00
Well that would explain it. Should have RTFM. Thanks for schooling me.

**Comment by jvbsl** [comment] 2020-04-30 22:35
I think this one is resolved, if not please open a new issue.

**Closed by jvbsl** 2020-04-30 22:35 UTC
