### ISSUE TITLE
CapsLock value not exposed in GameWindow.KeyDown and KeyUp event args

### ISSUE THREAD

**Issue by KinsonDigital** [opentk/opentk#1089] opened 2020-07-07 00:37 UTC
### Description

When using the **Modifiers** property on the **KeyboardKeyEventArgs** method parameter in the **GameWindow.KeyDown** and **KeyUp** events, the **CapsLock** enum value is missing.  This is preventing the check of the **CapsLock** modifier which prevents the ability to know if the **CapsLock** is on or off.

### Repro steps

1. Create a new instance of the **GameWindow** type
2. Register an event method to the **KeyDown** or **KeyUp** events
3. Inside of the event method, look at the **obj.Modifiers** parameter property to observe the full qualified name
   * You will see that this enumeration does not have a **CapsLock** value available.  The fully qualified name is **OpenToolkit.Windowing.Common.Input.KeyModifiers**

### Expected behavior

The available enumeration values in the list below should be visible and usable:
1. Alt
2. CapsLock
3. Control
4. NumLock
5. Shift
6. Super

### Actual behavior

The only choices available are in the list below:
1. Alt
2. Command
3. Control
4. Shift

### Related information 

* Operating system: Windows
* OpenTK Nuget Version: 4.0.0-pre9.1
* Runtime: CoreCLR

**Comment by NogginBops** [comment] 2020-07-07 00:51
A workaround is to hook up your own glfw key-hook directly instead of letting `NativeWindow` handle that (messy but will work).

The issue is that we are translating the key modifiers we get from glfw into ones that we know in OpenTK, when doing this translation we loose a few modifiers. 
Here is the code responsible:
https://github.com/opentk/opentk/blob/master/src/OpenToolkit.Windowing.Desktop/NativeWindow.cs#L1459-L1484

**Comment by varon** [comment] 2020-10-01 10:39
Should b fixed by #1090

**Closed by varon** 2020-10-01 10:39 UTC
