### ISSUE TITLE
PlatformNotSupportedException in WindowsFormHost 

### ISSUE THREAD

**Issue by bentorkington** [opentk/opentk#460] opened 2016-12-10 03:14 UTC
### Description

Calling GLControl.MakeCurrent() throws a PlatformNotSupportedException.

Sample code at https://github.com/thefiddler/opentk-wpf seems to work under OpenTK version 1.1.1153, but not version 2.0.0

### Repro steps

1. Create a WPF Window which includes a WindowsFormsHost. Set a callback for the Intialized event.

2. In the Initialized event, create a new GLControl

3. Call MakeCurrent() on the instance of GLControl

### Expected behavior

MakeCurrent() succeeds

### Actual behavior

PlatformNotSupportedException is thrown in GLControl.dll

### Related information 

Windows 10
OpenTL via NuGet
Sample code at https://github.com/thefiddler/opentk-wpf
Tried .NET versions 4 thru 4.52
Workaround by using OpenTK.dll version 1.1.1153 that accompanies the sample code

**Comment by bentorkington** [comment] 2016-12-10 03:18
Oh gosh, I didn't spot it from the description, but this seems to be a duplicate of #457. Hope this provides helpful additional info at least. @cpages

**Comment by kiwidoggie** [comment] 2016-12-16 01:48
I'm having the exact same issue,

`m_GlControl = new GLControl(GraphicsMode.Default, 4, 4, GraphicsContextFlags.ForwardCompatible)
            {
                Dock = DockStyle.Fill,
                VSync = false
            };`

Crashes there. With NoSupportedException. And my GPU supports up to 4.5 GTX 780.

**Comment by bravomikekilo** [comment] 2017-04-10 13:44
Will this problem be fixed?
Or is there another method to use OpenTK in WPF without GLControl

**Comment by ehtick** [comment] 2017-04-10 13:52
No problem for me with the GLControl in a Wpf control.

**Comment by bravomikekilo** [comment] 2017-04-10 14:03
could you show your GLControl argument?
I tried 4.4 and 2.0, all of them boom. My card should support openGL4.4

**Comment by ehtick** [comment] 2017-04-23 10:39
What i did is not use in the designer, just create it in code and set the windowsform host child;.

**Comment by winterhell** [comment] 2017-04-24 08:40
The NuGet releases seem to cause a lot of troubles

**Comment by ehtick** [comment] 2017-04-24 09:10
I think these versions are not compatible anymore.

**Comment by varon** [comment] 2017-06-11 22:47
Duplicate of #457

**Closed by varon** 2017-06-11 22:47 UTC
