### ISSUE TITLE
Posible input desynchronisation?

### ISSUE THREAD

**Issue by VPeruS** [opentk/opentk#548] opened 2017-06-22 09:17 UTC
OpenTK has two different Keyboard states which can be used at same time. Why window just doesn't use driver state? 
Code lines:
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/NativeWindowBase.cs#L58
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/X11/X11Keyboard.cs#L43

**Comment by Nihlus** [comment] 2017-06-22 10:05
Test it and see if there is an actual issue. OpenTK is a very large and very old codebase, and general design & structure questions like these are difficult to answer. Still, I appreciate that you're bringing it to our attention.

Closing until an actual issue is shown.

**Closed by Nihlus** 2017-06-22 10:05 UTC
Labels: not a bug

**Comment by varon** [comment] 2017-06-22 11:32
Well, the issue is that there's two ways of doing the same thing.

Ideally the NativeWindowBase should be refactored to use Keyboard.GetState() to avoid wierd issues.
