### ISSUE TITLE
 GL.ProgramParameter Cause linkprogram error

### ISSUE THREAD

**Issue by TangChen160186** [opentk/opentk#1515] opened 2022-09-28 02:27 UTC
### Description

![image](https://user-images.githubusercontent.com/66821836/192673347-e084fd06-fcdb-40dc-8468-51b11fcccc44.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/66821836/192673649-b51f73fc-2cdd-47b0-8554-40a351a72453.png)

### Related information 

* Operating system
* SDL or Native backend (if using OpenTK 4.7.5)
* What version of OpenTK (Installer, NuGet, Source Code)
* What runtime (.NET Framework, CoreCLR, Mono)
* Workarounds (if any)

**Comment by TangChen160186** [comment] 2022-09-28 02:29
![image](https://user-images.githubusercontent.com/66821836/192673861-8f794f62-63c1-4c43-ad1b-69cc3a9e7b79.png)
![image](https://user-images.githubusercontent.com/66821836/192673905-17748b5f-5d7e-47f4-821e-4dfb564e9c2c.png)

**Comment by utkumaden** [comment] 2022-09-28 05:11
This is an GLSL usage error and not directly an error from OpenTK itself. You should link us the shader stages associated with the the error (so the fragment and vertex shader code or others if any).

For questions like this it is more efficient to come to our [discord server] as we can more quickly help you diagnose issues, usually in real time.

[discord server]: https://discord.gg/6HqD48s

**Comment by TangChen160186** [comment] 2022-09-28 05:25
it's the opentk problem！！
**### vertexShader:**
![image](https://user-images.githubusercontent.com/66821836/192694372-0bca289b-c1b1-4f59-8ca8-e10d190f8f25.png)

**### fragmentShader:**
![image](https://user-images.githubusercontent.com/66821836/192694456-34ca1320-00d9-4c92-9f7b-b5ec504280d9.png)

If successful, a triangle should be rendered,but not!

If I put two shaders in one program, it is successful

**Comment by TangChen160186** [comment] 2022-09-28 05:27
When I use vertexShader, the above link error will appear. When I use other fragments, the link error will not appear

**Comment by TangChen160186** [comment] 2022-09-28 05:28
**### framgentShader**
![image](https://user-images.githubusercontent.com/66821836/192695074-42f8f569-bae7-4180-9b72-7d4d61ad042b.png)

**Comment by utkumaden** [comment] 2022-09-28 05:33
The issue is the fragment shader cannot use an input attribute directly. You need the vertex stage to relay the data. This is not correct GLSL, you can verify it by using the reference compiler, GLSLangValidator.

Change your shader code like this.

### Vertex
```glsl
#version 330
layout (location = 0) in vec3 aPosition;
out vec3 fPosition;

void main()
{
    fPosition = aPosition;
    gl_Position = vec4(aPosition, 1.0);
}
```

### Fragment
```glsl
#version 330
in vec3 fPosition;
out vec4 outputColor;

void main()
{
   outputColor = vec4(fPosition, 1.0);
}
```

## Appendix: Compiling your code with glslangvalidator
```
$ glslangValidator shader.frag shader.vert
shader.frag
ERROR: 0:2: 'location qualifier on input' : not supported for this version or the enabled extensions 
ERROR: 1 compilation errors.  No code generated.


shader.vert
```

**Comment by NogginBops** [comment] 2022-09-28 05:54
From the looks of it it seems like you are trying to link a program created by glCreateShaderProgram . This is not how this function works according to the documentation.

The function returns a separable program meant to be used with program pipeline objects. And you don't call glLinkProgram on those programs. See this so question for more information: 
https://stackoverflow.com/questions/27777226/how-to-use-glcreateshaderprogram

**Comment by TangChen160186** [comment] 2022-09-28 06:01
My code is as follows
![image](https://user-images.githubusercontent.com/66821836/192699391-93b46360-d006-447c-9597-e6da8a3356b4.png)

shader code  is as follows
**#vertex**
![image](https://user-images.githubusercontent.com/66821836/192699545-c87cef27-39e6-4c2c-af8f-f8ed9b8d0396.png)

**fragment**
![image](https://user-images.githubusercontent.com/66821836/192699679-6df72ca1-352b-41ad-b4dc-23246d83501d.png)

He still doesn't show triangles!
Please help me!

**Comment by NogginBops** [comment] 2022-09-28 20:55
Closing this issue as it seems like it's been resolved in the discord.

**Closed by NogginBops** 2022-09-28 20:55 UTC
