### ISSUE TITLE
Crash with latest GLControl Source.

### ISSUE THREAD

**Issue by AraHaan** [opentk/opentk#465] opened 2016-12-18 21:30 UTC
### Description

OpenTK.GLControl Crashes with no exception on Windows.

### Repro steps

Please provide the steps required to reproduce the problem

1. Clone from github
2. Build
3. Reference to a project using GlControl.
4. Crash with no exception whatsoever.

### Expected behavior

Everything to work fine.

### Actual behavior

Crash.

### Related information 

* Operating system: Windows 7 SP1 Ultimate x64 Build 7601
* SDL or Native backend: Native (I think)
* What version of OpenTK (Installer, NuGet, Source Code): Source
* What runtime (.NET Framework, CoreCLR, Mono): .NET 4.6.2
* Workarounds (if any): Not known yet.

**Comment by darko93** [comment] 2017-02-05 15:29
Have exactly the same issue.

**Comment by ThomasD13** [comment] 2017-03-01 20:10
Could you provide a complete project which crashes on your machine?

**Comment by varon** [comment] 2017-06-11 18:22
Closing, not because this is fixed, but because it seems to be a duplicate of #432.

**Closed by varon** 2017-06-11 18:22 UTC
