### ISSUE TITLE
Input conflict with some laptop volume buttons or keys

### ISSUE THREAD

**Issue by NinjaFighter** [opentk/opentk#396] opened 2016-05-30 06:58 UTC
I have two notebooks, HP and Alienware m17, and when I press the key or button for decrease volume, it triggered the keydown event just like key "C" is down.

**Comment by varon** [comment] 2016-05-30 13:24
Thanks for the report, @NinjaFighter!

Could you give us some code you're using to reproduce it, as well as a bit more info on your laptop make/model? Bonus points for an actual photograph of your keyboard, because those can vary quite a bit.

**Comment by tzachshabtay** [comment] 2016-05-30 17:14
Are those running on Windows?
If they are, it might be useful to test with pull request #269

**Comment by NinjaFighter** [comment] 2016-05-31 05:37
It happens on KeyDown event of GameWindow, so... GameWindow example project is enough to reproduce this.
I'm using windows on both laptops.
Actually my laptop are these: Dell Alienware m17x
Here's an image: http://images.anandtech.com/doci/6311/Small%20(9%20of%209).jpg
And the keyboard layout: https://i.ytimg.com/vi/z-fH5ilDxFY/maxresdefault.jpg
The increase and decrease buttons are on right top section.

The other is an HP Envy 14 Beats Edition
And here's an image of the keyboard layout: http://www.computershopper.com/var/ezwebin_site/storage/images/media/images/hp-envy-14-backlit-keyboard/639666-1-eng-US/hp-envy-14-backlit-keyboard.jpg

Buttons for decrease and increase volume are fn + F7 and fn + F8 Respectively.
At least I can see that in the two machines, the decrease volume button triggered the Keydown event with 'C' key.

**Comment by tyronx** [comment] 2016-06-28 07:42
This also happens with my Dell Inspiron 15z - increaing volumn with Fn+F12 triggers the key 'B'

**Comment by tyronx** [comment] 2016-06-28 08:17
I had a go at debugging this. The bug seems to stem from WinKeyMap.TranslateKey(). I can see 2 parameters passed there when I press Fn+F12. 
- short scancode contains 48
- VirtualKeys vKey contains VOLUME_UP

In line 174 the code Key key = GetKey(scancode); turns 48 into a "B" and the vKey is jsut ignored.

**Comment by varon** [comment] 2017-06-08 13:41
Closing as the related PR would need to be re-based. If we encounter issues again, please open a new PR.

**Closed by varon** 2017-06-08 13:41 UTC
