### ISSUE TITLE
System.AccessViolationException in OpenTK sample

### ISSUE THREAD

**Issue by VenkatachalamChinnakannu** [opentk/opentk#1027] opened 2020-03-27 09:37 UTC
**Description**

We downloaded the Learn OpenTK sample solution from GitHub (https://github.com/opentk/LearnOpenTK) and set **2-HelloTriangle** project as start up project and run.

We are getting System.AccessViolationException in _vertexBufferObject = GL.GenBuffer();  from  Window.cs file.
 
 **Expected behavior**

It should run without AccessViolationException

### Actual behavior

AccessViolationException

### Related information 

* Operating system
Windows 7 Professional
* SDL or Native backend
* What version of OpenTK (, NuGet, Source Code)
OpenTK 3.1.0
* What runtime (.NET Framework, CoreCLR, Mono)
.Net Framework 4.7.2
* Workarounds (if any)

**Comment by HugoPeters1024** [comment] 2020-04-27 16:55
![Screenshot from 2020-04-27 18-53-05](https://user-images.githubusercontent.com/22196124/80398794-79614800-88b8-11ea-938d-9b86b0f5d05d.png)

This is from the OpenTK discord, I know it targets version 4.0+ but I guess it's worth a shot

**Comment by NogginBops** [comment] 2020-04-27 18:07
Loading the bindings is a pure 4.0 thing. Shouldn't affect 3.1. Usually access violations don't appear at the place that caused them (they are usually caused by draw calls drawing more stuff than there are in the bound buffers). I would recommend seeing if there are any new commits in that repo and try it again. If the problem still persists I would try putting a few `GL.GetError()` calls around the place to see if you can figure out where it actually goes wrong.

**Comment by NogginBops** [comment] 2020-10-25 13:38
This is fixed in the 4.0 release. So this issue can be closed.

**Closed** 2020-10-25 20:54 UTC
