### ISSUE TITLE
Unable to use OpenTK 2.0 or latest 3.0 Pre with Xamarin.Mac application. (OpenTK 2.0 ad 3.0 with Xamarin.Mac crash )

### ISSUE THREAD

**Issue by dumbme24** [opentk/opentk#647] opened 2017-08-30 18:18 UTC
### Description
Unable to use OpenTK 2.0 with Xamarin.Mac application under Mono  + .NET 4.5 framework.
I am looking to use the OpenTk 2.0 or higher in Xamarin.Mac project but the app is crashing at runtime. The Xamarin.Mac is using framework Mono/.NET 4.5. 
I thought there could be a compatibility issues with OpenTK 2.0 platform and my Xamarin.Mac application platform.
Is OpenTK 2.0 or latest on Mac OS is supported with a Mno/.NET framework or Xamarin.Mac Mobile framework or Xamarin.Mac Modern framework ?

**EXCEPTION : System.TypeLoadException: Could not resolve type with token xxxxx...**

### Repro steps
Add OpenTk 2.0 in Xamarin.Mac project which is supported under Mono/.NET 4.5 framework. 
Define any of the members or properties of OpenTk 2.0 in application and compile the project. 
Project will get compile. But at runtime the application crashes.

### Expected behavior
Looking for a compatible version of OpenTk 2.0 or higher version (Latest version) that I can use with Xamarin.Mac application under Mono/.NET 4.5 framework..

### Actual behavior
Application crashes at runtime when any of OpenTK 2.0 program functionality added in Xamarin Mac project under Mono + .NET 4.5 framework..

Please provide a description of the actual behavior you observe.

### Related information 

* Operating system - 
 iMac  Sierra- Same issue on Mac 
* SDL or Native backend
* What version of OpenTK (Installer, NuGet, Source Code) - Latest Source Code - Develop Branch
* What runtime (.NET Framework, CoreCLR, Mono) - Mono + .NET 4.5
* Workarounds (if any)

**Comment by winterhell** [comment] 2017-08-30 18:52
Newest source runs on .net 2.0 and higher.
Here on Windows 7 it builds fine with build.cmd.
If you are trying to drop down replace Xamarin's version of OpenTK with this OpenTK it might not work depending on the platform. They are not 100% swappable.

**Comment by dumbme24** [comment] 2017-08-30 18:56
@winterhell Is there any Xamarin.Mac version of OpenTK 2.0 or higher?

**Comment by winterhell** [comment] 2017-08-30 18:58
If this OpenTK has versions that work on Xamarin.Mac, or how close it is to fully function, I cannot tell.
Other than that, have you tried this
https://developer.xamarin.com/guides/mac/platform-features/opentk/

**Comment by dumbme24** [comment] 2017-08-30 21:53
@winterhell Yes am able to use OpenTK 0.0 version in Xamarin.Mac application but OpenTk 2.0 and later with having functionalities like GraphicsContext etc is throwing a runtime exception even if declared as a member variable. I am able to use the functionalities of OpenTK 2.0 with all GL properies etc. But other newly added functionalities are not supporting in my Xamarin.Mac application. But I got these functionalities for windows application and now giving issue for the Mac application (Xamarin.mac).

**Comment by dumbme24** [comment] 2017-08-30 22:15
Similar issue in 2.0 version as well #482.

**Comment by dumbme24** [comment] 2017-08-31 00:33
Using Alias for OpenTK namespace is also not solving the issue.

**Comment by varon** [comment] 2017-09-08 22:55
Nobody on the team is presently using it in this configuration.

If you do manage to solve it, please let us know.

**Comment by Sappharad** [comment] 2017-10-11 01:52
@dumbme24 If you rename OpenTK.dll to something else, like OpenTK3.dll, for your scenario is the behavior the same? (This requires you to have a copy of the DLLs and reference them directly instead of via Nuget, of course)

I'm dealing with a slightly different situation, but in one instance I was finding that my reference to OpenTK.dll was being completely ignored and it was using the crusty old one from Xamarin.Mac instead. In my case the real problem is that the NMP looks at OpenTK.dll, sees references to both OpenGL and OpenGL ES and tries to link both. But fails because there is no OpenGL ES on a desktop. I don't know if this problem is specific to me, but perhaps you could confirm by renaming the DLL and referencing it manually to see if that happens for you?

**Comment by Sappharad** [comment] 2017-11-01 03:31
Following up on my previous post, I confirmed that OpenGL ES was the cause of the problems - at least in my case.
I grabbed the latest code from opentk-develop and just ripped out all of the OpenGL ES stuff. This involved removing the 5 ES### directories from the project, and making sure OPENGLES was not defined anymore in both the release and debug configurations. This may have been overkill, but I didn't need ES. After building again with the build.sh script, the resulting OpenTK.dll now works correctly with a 64-bit Xamarin.Mac application.

In summary, there were two problems:
1. Xamarin.Mac sees you trying to use OpenTK.dll and just links to its own version. This only seems to happen when your Target Framework is set to Xamarin.Mac. If pick an "Unsupported" framework like .NET 4.6.2 from Target Framework in General settings for the project, this problem goes away. Or just rename OpenTK.dll to something else like OpenTK3.dll.
2. The nmp linker tries to resolve references to native libraries, sees OpenGL ES and tries to link it anyway, even though OpenGLES.framework does not exist on desktop macs.

I don't know how you officially want to resolve this going forward, but I can post my builds if someone doesn't want to repeat the process of ripping out ES themselves. Maybe problems 1 and 2 need to be reported to Xamarin?

**Comment by Sappharad** [comment] 2018-01-10 03:01
Just a heads-up, the work-around I mentioned in my previous post no longer works as of recently. I don't know exactly when it broke, but it must have been a Visual Studio / Xamarin.Mac update at some point between mid-November and now. Everything builds correctly, but fails at runtime due to a type resolving exception. (And no, deleting bin and obj folders does not solve this)

Technically, the work-around is fine, but Xamarin seems to be doing something evil now and forces their own DLL of OpenTK to be used no matter what I've tried. The resulting app ends up with their version in the MonoBundle, even if you rename your build to something else. Swapping the DLL inside the bundle for the custom one that should be there instead sort-of works, as it doesn't crash instantly, but breaks stuff anyway because I assume something is expecting theirs. I'm positive that it's doing this, because the DLL that ends up in my app is identical to the one in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.0.0.215/lib/reference/net_4_5/

My new work-around is: In addition to stripping out the OpenGL ES stuff, you also need to rename the Assembly to OpenTK3 instead of OpenTK. If you do that, it properly uses the custom OpenTK build instead of theirs. This is the only solution that I found to get my stuff working again. I think I should probably file a complaint with Xamarin about this one.

**Closed** 2018-04-30 17:50 UTC
Labels: help wanted

**Comment by Sappharad** [comment] 2018-04-30 23:10
@Nihlus Can you tag which commit solved this, or did you close it by accident?

**Comment by Nihlus** [comment] 2018-05-01 08:07
@Sappharad There is no solution that's been merged to the repo. This issue is not with the OpenTK project, but rather with how Xamarin has handled the bundling of the library. Due to the continuing issues with how they use OpenTK and our own inability to help or otherwise change that, I'm closing the issue.

Any and all questions or complaints should be directed at Xamarin, not us.

**Comment by jlewin** [comment] 2018-07-26 20:37
>There is no solution...I'm closing the issue. Any and all questions or complaints should be directed at Xamarin, not us.

Does the mean Mac is being dropped as a platform? If not, are there any working Mac examples on recent OpenTK/Mono builds? 

I'd love to upgrade our project to more modern builds of OpenTK but every time I try I run into roadblocks and can't get the published NuGet packages to work.

**Comment by Nihlus** [comment] 2018-07-26 20:39
Mac is not being dropped as a platform, but we cannot provide support for Xamarin as they've chosen to break compatibility with mainline OpenTK in such a way that the issue is out of our hands. Complain to Xamarin.

**Comment by jlewin** [comment] 2018-07-26 22:17
@Nihlus  - I mean no disrespect and have significant gratitude for the work you guys are doing on the project. Additionally, I get that Xamarin using and breaking things in the OpenTK namespace is outside of your hands, however I'm still confused by the current level of Mac support and would appreciate any clarification you can provide  

> Mac is not being dropped as a platform

Do any recent releases of OpenTK work on a Mac with any recent version of Mono (v4.5+)? Are there any example projects that one could use to confirm or use as a model for upgrading older projects?

>we cannot provide support for Xamarin as they've chosen to break compatibility with mainline OpenTK in such a way that the issue is out of our hands

What does that mean for the future of Mac support? It sounds a lot like OpenTK on Mac/Mono simply doesn't work and isn't supported

The suggestion that Mac remains a supported platform doesn't jive with the reality I face when I pull in the latest NuGet packages and run into the same blocking errors described in this bug. When the bug is closed and reasoning is along the lines of "it's not our problem/there's nothing we can do", I'm left dead in the water

**Comment by jlewin** [comment] 2018-07-26 22:57
Thanks so much for the insightful response and clarification around Mac versus Xamarin SDK support. I've been frustrated in the past by the suggestion that things should be working when I experience the opposite with our project. Understanding that clean a Mac project free of the Xamarin SDK works totally clarify what I've been missing. 

We're currently using Xamarin.Mac bindings in a number of assemblies and are likely stuck for now but there may be an opportunity to isolate the two dependencies to mitigate the conflict.

Finally, I've spent a good chunk of time looking for samples and/or full blow apps but haven't ever come across [!osu](https://github.com/ppy/osu) . l'll definitely check it out and look forward to some point in the future when OpenTK samples are restored with some basic boiler plate projects for each platform.

**Comment by Nihlus** [comment] 2018-07-26 23:01
I'm glad to have helped :) We are moving to a significantly different architecture for the next major release of the library, which might go either way in resolving these issues. Time will tell.

**Comment by Sappharad** [comment] 2018-07-27 00:20
@jlewin Please be aware that the work-around I mentioned earlier in this thread still works. I am using Xamarin.Mac with OpenTK 3 and Eto Framework along with the Eto.Gl control. If you want the built binary I'm using, you can grab it here:
https://github.com/Sappharad/BizHawk/blob/master/References/OpenTK3.dll

But it's based on code that I pulled down from OpenTK master last October, so if there are any newer changes that you want you'll probably have to roll your own build because I'm not planning to make a newer build until I find a reason to need one. Just be aware that the namespace and DLL name was changed from OpenTK to OpenTK3 in order to avoid Xamarin.Mac conflicting with it.

For the reasons that @Nihlus mentioned above, I've also been worried that I shouldn't have wasted my time trying to use OpenGL, but it was the best option for what I wanted to do and still is. I need to be able to rely on other people's changes outside of macOS without having to make changes of my own for macOS. I'm not a fan of Apple's decision to drop OpenGL either. Since the developer of the Vulkan to Metal wrapper open sourced that last year, I'm hoping Vulkan will be a feasible alternative to OpenGL at some point.
