### ISSUE TITLE
No TargetFrameworks set in Nuget Package

### ISSUE THREAD

**Issue by patrick-dmxc** [opentk/opentk#1676] opened 2023-10-29 15:22 UTC
### Description

On Nuget the Package is not provided with TargetFrameworkts, this causes issues in VS 2022

### Repro steps

[Open Nuget OpenTK Package online](https://www.nuget.org/packages/OpenTK/#supportedframeworks-body-tab)

**Comment by NogginBops** [comment] 2023-10-29 19:51
What kind of issue are you experiencing? Can you show the actual error message you are getting?

**Comment by NogginBops** [comment] 2023-10-30 14:23
The issue you are seeing is not caused by the what you are describing. The OpenTK nuget package is a meta package that doesn't actually contain any code, so nuget displays the package as having no version. The dependent packages have correctly marked versions in them.

Your issue is that you are targeting `net6.0` while referencing OpenTK `3.2.0` which only supports running on `.net framework`. So to fix the issue you would either have to update to OpenTK 4 or use .net framework (which can be undesirable).

**Comment by NogginBops** [comment] 2024-03-25 13:24
Closing this issue as it isn't really an issue.
Feel free to reopen the issue if you feel there is still something to fix.

**Closed by NogginBops** 2024-03-25 13:24 UTC
Labels: needs verification, 4.x, buildsystem
