### ISSUE TITLE
the forum and wiki are trashed with spam

### ISSUE THREAD

**Issue by SoundGoddess** [opentk/opentk#410] opened 2016-07-13 08:16 UTC
I've done a lot of webmaster type stuff so if you'll want help cleaning up the mess I'd like to volunteer.  I want to learn this framework, but I have some issues with OCD and the site in its current state is somewhat unusable for me.

**Comment by varon** [comment] 2016-07-13 12:43
Thanks for the really generous offer, @SoundGoddess!

We're completely aware of the issue, and are actually busy putting the final touches on a completely new website, as we've decided that the old one is salvageable. You can view our progress here: https://amulware.github.io/opentk-gitpages/

**Comment by SoundGoddess** [comment] 2016-07-13 23:44
Oh cool, I like the new site design.  Are you ditching the forum for gitter?

Let me know if you need help with the transition.

**Comment by varon** [comment] 2016-07-14 15:42
For now, the first step is to ditch the existing website. We can look at setting up a new forum, but it's significantly less urgent that Github and Gitter exist.

**Comment by cra0zy** [comment] 2016-07-14 21:27
This is a duplicate of #389, continue the discussion there.

**Closed by cra0zy** 2016-07-14 21:27 UTC
