### ISSUE TITLE
Build fails on test (BorderStyle)

### ISSUE THREAD

**Issue by Aides359** [opentk/opentk#743] opened 2018-03-16 21:51 UTC
### Description

Build fails with failing test ` OpenTK.Tests.Integration.GameWindow+Borders.Updates to BorderStyle take effect [FAIL]`

### Repro steps

Follow build steps from readme.md

git clone https://github.com/opentk/opentk   # Download source code from git
cd opentk                                    # Enter the source directory
./build.sh                                     # Build on Mono (Linux / Mac OS X)

### Expected behavior

Build should run fine and output compiled lib

### Actual behavior

Build fails on BorderStyle test

    OpenTK.Tests.Integration.GameWindow+Borders.Updates to BorderStyle take effect [FAIL]
      Assert.Equal() Failure
      Expected: Fixed
      Actual:   Resizable
    [...]
    Running build failed.
    Error:
    xUnit2 reported an error (Error Code 1)

### Related information 

* Operating system: Linux
* What version of OpenTK (Installer, NuGet, Source Code): Source Code (HEAD, develop branch as per instructions no other branch should be checked out)
* What runtime (.NET Framework, CoreCLR, Mono): Mono

**Comment by Nihlus** [comment] 2018-03-16 22:18
We are aware of this. It's a problem with the asynchronous nature of the X11 backend - this causes updates to the window to intermittently fall behind the synchronous code.

Closing as a duplicate of #616.

**Closed by Nihlus** 2018-03-16 22:18 UTC
