### ISSUE TITLE
Remove checking MainThread

### ISSUE THREAD

**Issue by Hromon** [opentk/opentk#1206] opened 2020-11-24 13:50 UTC
### Description

I won't remove this code:

https://github.com/opentk/opentk/blob/d16e4f24572614a2b05493bf5472a2a4ae84dbe2/src/OpenTK.Windowing.Desktop/GLFWProvider.cs#L34
and
https://github.com/opentk/opentk/blob/d16e4f24572614a2b05493bf5472a2a4ae84dbe2/src/OpenTK.Windowing.Desktop/NativeWindow.cs#L568

I couldn't handle creating windows in other threads because of this and it's very bad. I had to spend time figuring out why it didn't work. I removed this chunk and the validation code in NativeWindow and everything works fine.

It is better to check the flow by ID for each window than to do this here!

### Version
OpenTK 4.3.0

### PS:
I'm not happy :<

**Comment by NogginBops** [comment] 2020-11-24 16:34
Can you explain in more detail what you are trying to do and how you would want this code to be changed?

**Comment by Hromon** [comment] 2020-11-24 18:27
This:
![image](https://user-images.githubusercontent.com/29508584/100136202-c384c900-2e9b-11eb-9f39-5bcc8472059a.png)

**Comment by NogginBops** [comment] 2020-11-24 19:23
GLFW doesn't allow you to create windows on different threads. 
This is because different operating systems behave differently not allowing consistent results.

- Cocoa (macos) will only send window events to the main thread.
- Win32 will send window events to the thread from which the window was created.
- X11 will send window events to only one thread but it doesn't need to be the main one.

Pure GLFW allows creating windows from different threads but by doing so you will not be cross platform by default.

The solution is to create all windows from the main thread and then processing rendering on different threads using the context functions.
https://github.com/glfw/glfw/blob/master/tests/threads.c

**Comment by Hromon** [comment] 2020-11-24 19:53
Then it is worth making it an option.

**Comment by varon** [comment] 2020-11-25 20:18
@Hromon  - If you can put together a PR for this with we can look at adding this feature. Closing for now this is not a bug.

**Comment by varon** [comment] 2020-11-26 05:44
After additional consideration, this is something we should reopen.

**Comment by uzername** [comment] 2020-11-26 16:49
All opengl tutorials state that it's better to have a single OpenGL context opened and associated with main thread.

**Comment by varon** [comment] 2020-11-28 18:02
@uzername  - I agree completely, but at the same time if we had this as an opt-in option, it would be a convenient feature for some cases.

**Comment by NogginBops** [comment] 2022-04-13 14:34
I'm going to link this commit here as it seems to remove this check entirely.
https://github.com/opentk/opentk/commit/5361d02bb3918ed02e65628cc210de184c9e9c43
From this PR: https://github.com/opentk/opentk/pull/976

**Comment by NogginBops** [comment] 2022-04-14 16:00
I'm going to close this as it seems like this is fixed.
If we introduce a "proper" check in the future I will make sure that it's possible to turn off such a check.

**Closed by NogginBops** 2022-04-14 16:00 UTC
Labels: not a bug, 4.x, glfw

**Comment by NogginBops** [comment] 2022-04-14 18:15
I added proper checking for the main thread in #1429, use `GLFWProvider.CheckForMainThread = false` to turn this off.
