### ISSUE TITLE
OpenTK.Input problem

### ISSUE THREAD

**Issue by alexfevery** [opentk/opentk#475] opened 2017-01-19 21:14 UTC
### Description

The OpenTK.Input in version 2.0 has a strange issue where suddenly Mouse.GetState() and Keyboard.GetState() will stop working. Mouse.GetState().X and Y will return 0,0 and  iskeydown will always return false. 
When this happens Mouse.SetPosition() will still work

This problem occurs whenever the Load event takes more than a couple seconds to finish, either because you try to load too much stuff that takes a long time, or if you manually insert a sleep.

### Repro steps
enter following code in a new project version 2.0 
https://s24.postimg.org/uvaud175x/Capture.png

wait until you hear the beep and try to press the A key.   Then comment out the Thread.Sleep(5000) line and try again.   The sleep in the load event breaks OpenTK.Input.  

### Expected behavior

Keyboard.GetState() and Mouse.GetState() work and return the state

### Actual behavior

they are broken and don't

### Related information 

* Windows 10
* SDL or Native backend
* 2.0 installed with nuget
* .Net

EDITED TO UPDATE NEW INFORMATION

**Comment by winterhell** [comment] 2017-01-19 21:21
Can you build a test demo that showcases the problem?(like, write the state to the window title, if you dont have another text output on screen),
OR, has this worked with a different OpenTK build? If you havent tried that, you can check the one here https://sourceforge.net/projects/opentk/files/opentk/opentk-1.1/stable-5/

**Comment by alexfevery** [comment] 2017-01-19 21:57
It doesn't work with other opentk builds either.  I am trying to build a test demo. 

Before I called the function that caused the problem I had loaded a 200,000+ vertex object on the GPU memory. I never drew the object to the screen but commenting out the line where I loaded it fixed the problem. 

The object I loaded draws perfectly fine and I can run it at 1000+fps  but loading that + loading something else seems to cause OpenTK.Input to break.

I will experiment more and get back to you with a test case but I think the problem is related to loading large objects into memory, either the GPU memory or computer memory.

The program itself never used more than 300MB  so i think it might be related to single objects that are very large, over 100,000 vertices.

**Comment by alexfevery** [comment] 2017-01-19 22:30
I discovered the problem! It wasn't related to memory but time.  Reproducing it is extremely simple. Just write this code 
https://s30.postimg.org/4x197c05t/Capture.png

wait until it starts printing a's to the console and then press the "a" key yourself.  The breakpoint won't trigger. 

Comment out the Sleep line, and it works fine.

**Comment by varon** [comment] 2017-01-20 08:09
This is likely happening because you're not properly plumbing events.

Instead of using a while loop, try call `GameWindow.Run()`.

**Comment by alexfevery** [comment] 2017-01-20 13:25
No, It still happens.   Here you can try this code instead.
https://s24.postimg.org/uvaud175x/Capture.png

it is using gamewindow.Run() but still occurs.

**Comment by DannyGlover** [comment] 2017-02-08 00:15
I have the same issue

**Comment by varon** [comment] 2017-06-11 20:54
Tested this. Could not reproduce. Apparently fixed with 3.0.0-pre

**Closed by varon** 2017-06-11 20:54 UTC
