### ISSUE TITLE
Supporting .NET Core 1.0

### ISSUE THREAD

**Issue by xanather** [opentk/opentk#245] opened 2015-04-11 06:11 UTC
Ive started this issue to discuss if/how OpenTK will support .NET Core.

Originally made a post here a while ago: http://www.opentk.com/node/3915
I think as long as OpenTK supports BCL's it will support .NET Core. SharpDX recently did this to allow its assemblies to be consumed by the CoreCLR runtime.

Main things I see that might be needed:
1. Using System.Numerics.Vector (Mono should also have this by the time .NET Core releases). This is not necessary but may make some vector math operations faster.
2. Supporting BCL.
3. System.Drawing namespace could be an issue.

Once Visual Studio 2015 releases and .NET Core is integrated with it I'll see if I can work on supporting it if it hasn't been looked into by then.

**Comment by Frassle** [comment] 2015-04-11 08:45
Definitely something that needs looking into. The vector stuff could be a massive gain! There's a lot of reasons to get rid of System.Drawing but it's quite pervasive through the code base, going to be a lot of API breaking changes when we get rid of it. I think if net45 is done as a mainting compatibility upgrade and then net50 we break everything (seeing as we'll probably need to redesign to take advantage of Numerics).

**Comment by xanather** [comment] 2015-04-11 09:19
I just noticed there is a chance something like System.Drawing could make it into .NET Core https://github.com/dotnet/corefx/issues/1363. May not need to remove System.Drawing namespace afterall, but it might be better to remove the System.Drawing dependency if anyone is willing to work through all that - otherwise it might not be necessary.

**Comment by thefiddler** [comment] 2015-05-11 09:52
Getting rid of System.Drawing is also important for OSX, as it is completely broken and can cause up to 5-minute delays on startup (this is a known bug in Mono.) It's actually not that hard to remove (IIRC compiling with `#define MINIMAL` already takes care of that), but the main sticking point is backwards compatibility. Public APIs that use System.Drawing include (from the top of my brain):
- `INativeWindow.Position / .Size / .ClientSize / .Bounds / .ClientBounds`
- `INativeWindow.Icon`. This is the hardest to reimplement.
- `OpenTK.Graphics.Color4`

If .Net Core maintains support for System.Drawing, then the biggest reason to remove this goes away. If it's dropped, then we should deprecate `INativeWindow.Icon` and offer an alternative similar to `INativeWindow.Cursor`. We can maintain support for the other APIs through a simple compatibility shim (see [OpenTK/Minimal.cs](https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Minimal.cs).) Then, depending on the profile we would compile out the deprecated/unsupported parts.

**Comment by mellinoe** [comment] 2015-05-14 01:00
Hey all, I'm on the .NET team at Microsoft and I'm glad to see there's already some discussion on bringing support for .NET Core. If there's some serious interest in this, I'd definitely be happy to help bring something up (even just a simple prototype for starters). I've tinkered around with porting OpenTK over, and have a REALLY rough version working, with some hacked-up dependencies:

https://github.com/mellinoe/opentk

A few things to note:

* Only works on Windows. I commented out a lot of the OSX/Linux-specific code because I don't have a machine to test those on (and because i was just trying to get a quick prototype running on windows).
* I used a very hacked-up version of System.Drawing that I compiled myself from the reference source code, modifying it slightly to compile against .NET Core, and removing some pointless stuff that I didn't feel like porting over.
* The Generator program needed some various changes in order to rewrite the assembly against the .NET Core contracts, rather than against mscorlib, etc. See [this change](https://github.com/mellinoe/opentk/commit/3df97f324708019140c9daa7f92d33085c5e24b3#diff-cbd91cf6632057f1352f5ed5ab6191e0)
* Features that aren't available in .NET Core had to be stripped out of the code; things like ISerializable, etc. I also made a few "Mocks" classes for things that were easy to emulate (like Debug.Print(), etc.) which aren't supported anymore, but in other cases I just deleted features to get things running. Presumably we can #if things like binary serialization and other optional features and try to use alternatives where they exist for other things.

Anyways, like I said, it's a very rough version, but it gives an idea of the level of work needed to get this up and running. Doing things "the right way" would obviously take a lot more planning and would need to be done much more carefully.

Eliminating the System.Drawing dependency would simplify things a bit further, as well. There is some discussion regarding supporting some subset of this library [here](https://github.com/dotnet/corefx/issues/1563). Regardless, we could probably come up with something to work either with or around this.

**Comment by ala53** [comment] 2015-05-31 20:07
Hey, Adding my 2 cents to this: CoreCLR also has a problem with the `InputThread.SetApartmentState(ApartmentState.STA);
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Syst
em.Threading.Thread.SetApartmentState(System.Threading.ApartmentState)'.
```

**Comment by mellinoe** [comment] 2015-08-12 23:32
(Not sure if anyone is following this issue any longer, but I'll post this here anyways)

Since VS 2015 is out, I gave a shot at adding a .NET Core-compatible build of OpenTK.dll, mostly based on my previous efforts I mentioned above. I also took changes to make the "Minimal" build configuration work correctly, to remove the System.Drawing dependency. I grabbed the changes from this PR: https://github.com/opentk/opentk/pull/262

See this commit for all my changes: https://github.com/mellinoe/opentk/commit/1b91afd7923f1754989a76c27532009413739de7

* Requires VS 2015, or at least MSBuild 14. Not sure that this will build on other platforms as-is right now so we would probably need to change some more settings in the project file to get it working everywhere.
* Only includes a project for OpenTK.dll (no tests). Didn't change the NuGet package yet.
* Only tested on Windows. I threw some NotImplementedException's on other platforms where I didn't know what to do.

**Comment by Frassle** [comment] 2015-08-13 07:08
Still following. PR #262 should probably be merged into master soon so if that helps with moving to Core double bonus!

**Comment by mellinoe** [comment] 2015-08-21 17:23
Small update:

* My Windows port seems to be working decently fine. I notice there's a few small issues in the parts that I've tested, like my window titles aren't setting property and their initial position is a bit weird (just based on my previous usages of OpenTK). I think I may have botched some of the PInvoke declarations related to those.
* I briefly tested the Linux version, but hit a blocker in CoreCLR; https://github.com/dotnet/coreclr/issues/1408. It seems calli hasn't yet been implemented for other platforms, which prevents me from getting very far given its usage here.

My plan was to wait for the above issue to be fixed, do some more validation on Linux, and then clean up the work and submit a PR.

**Comment by Frassle** [comment] 2015-08-21 22:30
PR #262 is now merged in, I guess the minimal configurations should be good base for .NET Core as well given it doesn't use System.Drawing.

Calli is for sure needed! All the interop is done using calli instructions so Linux will be blocked until the CoreCLR supports it.

**Comment by manu-silicon** [comment] 2015-08-23 06:11
I'm trying to compile against CoreCLR using @mellinoe's fork but it does not compile. I'd like to help but would like to start from the right place. My Goal is to have both OpenTK.dll and OpenTK.GLControl.dll compiled for CoreCLR.

**Comment by mellinoe** [comment] 2015-08-24 17:58
Hey @manu-silicon , I can help you get it building. Let me know what the specific errors you get are.

First: it requires VS 2015 to build, as it's using the new v3 NuGet packages. It will take some more work to get it independent of that.

Second: I have noticed that when opening it on a new machine for the first time, you have to force it to restore the NuGet packages, and I'm actually not sure how to do with the new NuGet UI. Uninstalling and re-installing any of the dependencies seems to force it to refresh/restore the packages. If you don't restore the packages, you will get a ton of errors like "System.Object is not defined", etc.

Other than that, it should be set up to build fine as-is

**Comment by manu-silicon** [comment] 2015-08-24 19:46
I tried with your netcore-port branch. I do use VS 2015 and the latest msbuild. What command line do you use to compile? As for .NET Core, I've actually building my own setup, see https://github.com/manu-silicon/corefxref on how to use this so that I do not have to fiddle too much with nuget.

**Comment by mellinoe** [comment] 2015-08-24 20:01
I have generally been using VS to build this, but it also works in the regular VS 2015 dev command prompt. I believe you just need to make sure you are using MSBuild 14. What are the errors you are seeing?

**Comment by manu-silicon** [comment] 2015-08-24 20:21
When I open the solution in VS 2105, I have an issue with the OpenTK.NETCore.csproj project. it is looking for the v5.0 directory in msbuild, but there I only have v4.5 and v4.6. I'm not sure if I'm mssing something in the VS 2015 or msbuild install. The error is:

C:\work\sharp\GitHub\opentk\Source\OpenTK\OpenTK.NETCore.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\work\sharp\GitHub\opentk\Source\OpenTK\OpenTK.NETCore.csproj

From the command line, when I do:

"\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe"  /p:Configuration=Release /p:Platform="Any CPU" OpenTK.sln

I'm getting some errors with respect to not finding some Mono.Cecil assemblies. Are we supposed to copy them ourself or is it part of the OpenTK package?

**Comment by dsplaisted** [comment] 2015-08-24 20:24
You need to install the Windows 10 tools to get the new Portable Class Library support.

-----Original Message-----

**Comment by manu-silicon** [comment] 2015-08-24 20:25
I'm realizing now that it should come from nuget. I've done a manual restore and it seems that it goes further. Getting an error in : 

Platform\Windows\API.cs(1787,29): error CS1503: Argument 2: cannot convert from 'int' to 'string' [C:\work\sharp\GitHub\opentk\Source\OpenTK\OpenTK.csproj]

**Comment by manu-silicon** [comment] 2015-08-24 20:39
@dsplaisted Thanks. I'm installing them and now I got the v5.0 folder.

**Comment by mellinoe** [comment] 2015-08-24 21:01
Ah yes, you will probably need that as well. Thanks for the suggestion, Daniel. All of the .NET/VS installers seem to blur together for me :smile:

**Comment by manu-silicon** [comment] 2015-08-24 21:55
getting further but I'm having some nuget issue:

C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(83,5): error : Couldn't find the required information in the lock file. Make
 sure you have .NETFramework,Version=v2.0 mentioned in your targets.

**Comment by mellinoe** [comment] 2015-08-24 22:11
Are you sure that is an issue with the OpenTK.NETCore project file? I think that may be from one of the other project files in the solution; some of them target older .NET versions. I just tried opening the solution on my second machine which has VS 2015 installed, and it gave a few errors when loading some of the other projects in the solution, because the machine didn't have the correct targeting packs for those versions installed. I just had it unload those projects.

That said, once I loaded the OpenTK.NETCore project, it restored and built just fine, and after that I could build from the command line as well.

**Comment by manu-silicon** [comment] 2015-08-24 22:18
I was using the main OpenTK.sln solution file. Did not realize that only the OpenTK.NETCore project would compile. Have you configured OpenTK.sln to be able to compile the NETCore project if providing some command line arguments to msbuild?

**Comment by mellinoe** [comment] 2015-08-24 22:40
Ah yes, it seems like a couple of other projects are failing to build for a couple of reasons. I'll add a commit that should fix that so that building the whole solution works again. The main problem is that the project.json file (the new NuGet descriptor file) is in the same folder as all of the OpenTK project files, so it is trying to restore packages for all of those projects, which won't work.

I haven't actually tested building the entire solution until now, mostly because I didn't make any changes except to the OpenTK source files. Should be fixed up in a minute.

**Comment by manu-silicon** [comment] 2015-10-28 07:15
I got back to this project and using some of @mellinoe 's work, I got a new set of changes to the project to make it compile under CoreCLR. See https://github.com/opentk/opentk/pull/308

**Comment by mellinoe** [comment] 2015-10-29 05:01
Awesome @manu-silicon , great to see this picking back up! Just today I was actually thinking of cleaning up my branch and getting a PR ready, but now I don't have to :smile: . I'll bring the discussion over to the PR.

**Comment by MaitreDede** [comment] 2017-08-24 07:55
Hi,
I am looking for possible things I can do with my Raspberry Pi 3 with dotnet, and I am trying to reproduce some sample programs originally written in C to C#. I am targetting `netstandard2.0`, and compiling self-contained applications. I have managed to handle some low-level native libraries, (like dispman, mmal...) and came the opengl question...
Does someone have a working version of OpenTK (at least OpenGL) that can be used on a `netstandard2.0` application, targetting `linux-arm` ?
I am trying to reproduce this sample : https://github.com/raspberrypi/firmware/tree/master/hardfp/opt/vc/src/hello_pi/hello_triangle

Thanks.

**Comment by Nihlus** [comment] 2017-08-24 10:13
@MaitreDede A netstandard2.0 release of OpenTK is planned for the 4.0 milestone. @mellinoe has a version compatible with .NET Core, which you could check out.

**Comment by mellinoe** [comment] 2017-08-24 17:57
Yes, you can try this package, which is compatible with .NET Core: https://www.nuget.org/packages/OpenTK.NETCore/.

Note that it is missing some of the changes and fixes that have been made in the master branch of OpenTK -- it's not fully up to date.

Alternatively, you could also pull down the branch from [this PR](https://github.com/opentk/opentk/pull/628) and build the .NET Standard 2.0 project. It is up to date as of 19 days ago.

**Comment by JimSEOW** [comment] 2017-08-30 08:32
@xanather the title should be **Supporting .NET Core 5.0/6.0**
For .NetStandard2.0 only works in UWP6.0

**Comment by 21c-HK** [comment] 2017-09-07 11:23
> the title should be Supporting .NET Core 5.0/6.0

.NET Core 5.0 is no longer called as such and confusing to anyone who has just recently heard of .NET Core. That version is called .NET Core 1.0 now (see https://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx). 

The .NET Core 2.0 was recently finalized.

**Comment by xanather** [comment] 2017-09-08 03:52
I renamed, when I created this issue .net core was called .NET Core 5.0.

**Comment by Nihlus** [comment] 2018-04-22 11:59
We're aiming for the 4.0 release to support .NET Standard 2.0. As it is, we've set a merge deadline for 3.0 on the 1st of May, whereafter work on 4.0 proper will begin.

**Comment by DannyGlover** [comment] 2018-04-22 23:41
@mellinoe Thanks for the information. I was using your port, but it's a little (seriously, it's great) rough around the edges (no offense).

I'll check out your new library in the mean time. Really appreciate your continued efforts towards a graphics library for .Net core.

@Nihlus That is fantastic to hear! I can't wait. Thank you for letting me know.

**Comment by mellinoe** [comment] 2018-04-23 01:26
> @mellinoe Thanks for the information. I was using your port, but it's a little (seriously, it's great) rough around the edges (no offense).

No offense taken 😄. The code is extremely old at this point, and I never intended on keeping it forked for long. It was too much work to try to keep in sync with mainline OpenTK, especially for a library that I'm no longer using.

**Comment by DylanFPS** [comment] 2018-11-25 18:59
Closing because 4.0 will (and already does on `master`) support .NET Standard 2.0 and compliant platforms 🎉

**Closed by DylanFPS** 2018-11-25 18:59 UTC
Labels: improvement, question / discussion
