### ISSUE TITLE
[4.0] Resolve namespace conflicts on Xamarin iOS and Android

### ISSUE THREAD

**Issue by Nihlus** [opentk/opentk#810] opened 2018-09-06 21:32 UTC
At the moment, consumers of OpenTK in mobile environments (iOS, Android) via Xamarin are either unable to or have large issues using more recent versions of OpenTK in their projects. Mainly, this is due to Xamarin's decision a few years back to bundle OpenTK 1.0's source code in their own source tree without changing the root namespace.

Thus, consumers now have to deal with a multitude of namespace conflicts and the hacky workarounds that follow. We can't reliably fix bugs or provide support to these consumers. Xamarin has, unfortunately, been frustratingly unwilling to work on a solution on their end, leaving us to mop up their mess.

In developing 4.0, we've taken the decision to make sweeping changes to the architecture and layout of the project. These changes are already massively breaking in nature, and will fundamentally change how OpenTK is consumed by project authors. Therefore, I think it's time we at least consider a solution to the Xamarin problem on our end - changing our root namespace.

By doing this, we'd be providing a clean break from Xamarin's bundled source, as well as from the legacy OpenTK codebase. The two API surfaces already differ significantly.

It isn't without its issues, however. Changing the root namespace is a big deal - it's a source-level break for *every file* that uses OpenTK in any way, and we'd have to do it everywhere in our own source tree. Any tutorial on the web about OpenTK, any blog post, any reference we have is now defunct and wrong, and needs to be corrected. 

This is something we need to, collectively, have a serious think about. I'm not certain that it's the best solution, or even a solution at all. It is, however, worth bringing up as a potential solution to the Xamarin issue. The best solution would, of course, be for Xamarin to correct things on their end and decouple the dependency, but so far they've made it clear that it's not something they're willing to do.

Therefore, I'd like to hear everyone's opinions on this, and the following more specific questions:

1. Is it feasible for OpenTK to change its root namespace?
2. Should we consider it as an option to resolve the conflict with Xamarin?
3. Are there any other solutions?
4. Is it worth it for us to spend the time and energy on this?

Related issues and relevant reading:
#388 
#482 
#494 
#647
https://bugzilla.xamarin.com/show_bug.cgi?id=18575
https://bugzilla.xamarin.com/show_bug.cgi?id=52168
https://bugzilla.xamarin.com/show_bug.cgi?id=52169
https://bugzilla.xamarin.com/show_bug.cgi?id=56017

**Comment by wcdeich4** [comment] 2018-09-06 21:49
Seems like a good idea

**Comment by VPeruS** [comment] 2018-09-06 22:31
Why not to propose Xamarin to remove opentk, did they have it as internal dependency?

**Comment by Nihlus** [comment] 2018-09-06 22:39
@VPeruS Tzachs already did, and was turned down. See https://bugzilla.xamarin.com/show_bug.cgi?id=52169.

**Comment by peppy** [comment] 2018-09-06 23:43
Just chiming in that this is a must for us, in order to support mobile platforms without hacks.

**Comment by varon** [comment] 2018-09-07 09:10
This is an excellent call.

I strongly suggest that we aim to get the ancient, broken, and unsupported fork of OpenTK removed from Xamarin. This might be possible now that Microsoft is in charge.

We should also open an issue on https://github.com/mono/opentk - it'll probably be ignored, but at least it should increase visibility of the problem.

@dalexsoto - Any chance you can help us this time?

**Comment by tzachshabtay** [comment] 2018-09-07 14:54
Another relevant issue: #479 

Answering specific questions:
1. Yes, it's feasible (definitely a lot of work). Regarding the concern of breaking all existing tutorials, I thought that the current V4 overhaul already breaks all tutorials regardless, so not a concern?
2. Yes, we should definitely consider this as a solution. Xamarin is the big fish and OpenTk is the small fish, and if they won't budge we need to adjust.
3. I can't think of any other practical solution. There is one impractical solution which I can offer, which would be to fork the xamarin projects...
4. Personally, for me, it's not worth it as I have managed to workaround this issue. But I remember some people were not able to workaround it, and it will majorly improve QOL for mobile devs, so it should definitely be a goal of the project. And now seems like a good opportunity as you're already breaking everything.

**Comment by VPeruS** [comment] 2018-09-07 19:35
They can pack it into nuget package and add as dep. Then user can with version that he want

**Comment by wcdeich4** [comment] 2018-09-08 18:26
My friends, it is a good idea to try to get Xamarin & IOS to do the right thing.  But let me also suggest you need to deal with the harsh realities of life if they do not .  I know what it like to work with dinosaur brained people who will not do the right thing no matter ho right your logic & is.  Even a small change, like Open_TK might e enough.  Or NewOpenTK, or NewTK........  whatever the is most popular

**Comment by varon** [comment] 2018-09-08 19:01
@wcdeich4 Yeah, we're prepared to deal with reality, but we also want to give them a chance to do the right thing.

**Comment by DylanFPS** [comment] 2018-09-20 17:29
All for this. Would recommend OpenToolkit.* and that way you can also reserve the NuGet prefix.

**Comment by Nihlus** [comment] 2018-09-20 19:46
I like that as a prefix. +1 on that suggestion.

**Comment by varon** [comment] 2018-10-19 01:53
I'll get onto trying to talk sense into xamarin/microsoft.

**Comment by varon** [comment] 2018-10-27 20:42
The maintainers have discussed this, and given the outcomes + possible solutions, we're going to swap namespaces to `Otk`.

_everything_ will be move over. This should allow a find/replace to get you up to speed.

Given how terribly Xamarin/Microsoft have handled this, we'd like to add a licensing clause that prevents Xamarin/Microsoft from using or including any new or updated versions of OpenTK. It's our intention to leave our users completely unaffected, but stop them from utilizing, copying, or forking OpenTK... again.

We would appreciate advice on how to do this effectively.

**Comment by jorolf** [comment] 2018-10-27 21:10
Why Otk and not OpenToolkit like previously suggested?

**Comment by varon** [comment] 2018-10-27 21:38
@jorolf - doesn't really matter, `Otk` is short simple, and we can almost certainly get the prefix on NuGet.org.

**Comment by jvbsl** [comment] 2018-10-28 08:57
I would have named it OpenToolKit anyway, because you would be able to see the initials of OpenTK then. Apart from that I don't care that much, and just think it's said to have been forced to change the namespace.

**Comment by varon** [comment] 2018-10-28 19:31
I'm not sure we should close this until we've actually moved the namespaces across, as the issue isn't fixed yet.

**Comment by peppy** [comment] 2018-10-30 19:32
I'd like to put a vote for not using a TLA namespace, as this is generally not done anywhere else in the .net ecosystem. `OpenToolkit` feels good to me.

**Comment by Nihlus** [comment] 2018-10-30 19:37
We're having some internal discussions on the namespace choice. At the moment, we're still pursuing an amicable solution with Xamarin, and we'd prefer to avoid changing the root at all. We'll make a final decision if and when that time rolls around.

**Comment by DylanFPS** [comment] 2018-10-30 19:38
Hi all,

Thanks for voicing your opinions. Unfortunately, we have already sent in
the reservation request for OTK, so it might be too late 😐

**Comment by VPeruS** [comment] 2018-10-31 16:45
Please, reopen this, it must be closed by pr.

**Comment by DylanFPS** [comment] 2018-10-31 16:55
We were unable to work out a solution with Xamarin, so we are pursuing the OTK namespace root. Apologies if this isn’t the result you wanted, I personally wish we didn’t have to change the namespace at all.

**Comment by FreezyLemon** [comment] 2018-11-01 18:10
Reservation request? 
I'd prefer `OpenToolkit` over `OTK`, too.. it just does not sound right

**Closed** 2018-11-02 22:05 UTC
Labels: Android, help wanted, iOS, not a bug, question / discussion
