### ISSUE TITLE
GetShaderSource requires StringBuilder to be sized appropriately in Linux

### ISSUE THREAD

**Issue by j1s1e1** [opentk/opentk#224] opened 2015-02-23 10:01 UTC
I was trying to use GetShaderSource and it crashed in Mono on Fedora 21 64 bit.  Note that I'm out of date, and using 1.1, but I didn't see any changes.  I ended up guessing and resizing the StringBuilder by adding the bufSize to the initialization of the StringBuilder:

		private String getShaderSource(int shader)
		{
			StringBuilder source;
			int length;
			int bufSize = 4096;
			source = new StringBuilder(bufSize);
			GL.GetShaderSource(shader, bufSize, out length, source);
			return source.ToString();
		}

This fixes the problem.  I imagine this could be done in the function call since source is an out variable so that no special handling would be required by the calling function.  In any case, I figured submitting a bug report would point anyone with similar problems in the right direction.

Thanks,

James

**Comment by Frassle** [comment] 2015-02-23 11:18
It's a known issue, see #204. I'm not sure what the best course of action to deal with it is. You can see some proposed solutions on that ticket, feel free to make a comment on which you feel better/worse, will help point us into making the right call.

I'll close this ticket as a duplicate of #204.

**Closed by Frassle** 2015-02-23 11:18 UTC
